package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 查询交易编码<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:2237</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcQryTradingCodeField extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	public byte[] InvestorID = new byte[13];
	/**
	 * 交易所代码<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	public byte[] ExchangeID = new byte[9];
	/**
	 * 客户代码<br>
	 * C type : TThostFtdcClientIDType
	 */
	public byte[] ClientID = new byte[11];
	/**
	 * 交易编码类型<br>
	 * C type : TThostFtdcClientIDTypeType
	 */
	public byte ClientIDType;
	public CThostFtdcQryTradingCodeField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "InvestorID", "ExchangeID", "ClientID", "ClientIDType");
	}
	/**
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param InvestorID 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType<br>
	 * @param ExchangeID 交易所代码<br>
	 * C type : TThostFtdcExchangeIDType<br>
	 * @param ClientID 客户代码<br>
	 * C type : TThostFtdcClientIDType<br>
	 * @param ClientIDType 交易编码类型<br>
	 * C type : TThostFtdcClientIDTypeType
	 */
	public CThostFtdcQryTradingCodeField(byte BrokerID[], byte InvestorID[], byte ExchangeID[], byte ClientID[], byte ClientIDType) {
		super();
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		if ((InvestorID.length != this.InvestorID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.InvestorID = InvestorID;
		if ((ExchangeID.length != this.ExchangeID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ExchangeID = ExchangeID;
		if ((ClientID.length != this.ClientID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ClientID = ClientID;
		this.ClientIDType = ClientIDType;
	}
	public static class ByReference extends CThostFtdcQryTradingCodeField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcQryTradingCodeField implements Structure.ByValue {
		
	};
}
