package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 正在同步中的交易账号<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:1909</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcSyncingTradingAccountField extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 投资者帐号<br>
	 * C type : TThostFtdcAccountIDType
	 */
	public byte[] AccountID = new byte[13];
	/**
	 * 上次质押金额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double PreMortgage;
	/**
	 * 上次信用额度<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double PreCredit;
	/**
	 * 上次存款额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double PreDeposit;
	/**
	 * 上次结算准备金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double PreBalance;
	/**
	 * 上次占用的保证金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double PreMargin;
	/**
	 * 利息基数<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double InterestBase;
	/**
	 * 利息收入<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double Interest;
	/**
	 * 入金金额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double Deposit;
	/**
	 * 出金金额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double Withdraw;
	/**
	 * 冻结的保证金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double FrozenMargin;
	/**
	 * 冻结的资金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double FrozenCash;
	/**
	 * 冻结的手续费<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double FrozenCommission;
	/**
	 * 当前保证金总额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double CurrMargin;
	/**
	 * 资金差额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double CashIn;
	/**
	 * 手续费<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double Commission;
	/**
	 * 平仓盈亏<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double CloseProfit;
	/**
	 * 持仓盈亏<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double PositionProfit;
	/**
	 * 期货结算准备金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double Balance;
	/**
	 * 可用资金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double Available;
	/**
	 * 可取资金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double WithdrawQuota;
	/**
	 * 基本准备金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double Reserve;
	/**
	 * 交易日<br>
	 * C type : TThostFtdcDateType
	 */
	public byte[] TradingDay = new byte[9];
	/**
	 * 结算编号<br>
	 * C type : TThostFtdcSettlementIDType
	 */
	public int SettlementID;
	/**
	 * 信用额度<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double Credit;
	/**
	 * 质押金额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double Mortgage;
	/**
	 * 交易所保证金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double ExchangeMargin;
	/**
	 * 投资者交割保证金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double DeliveryMargin;
	/**
	 * 交易所交割保证金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double ExchangeDeliveryMargin;
	/**
	 * 保底期货结算准备金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double ReserveBalance;
	/**
	 * 币种代码<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	public byte[] CurrencyID = new byte[4];
	/**
	 * 上次货币质入金额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double PreFundMortgageIn;
	/**
	 * 上次货币质出金额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double PreFundMortgageOut;
	/**
	 * 货币质入金额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double FundMortgageIn;
	/**
	 * 货币质出金额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double FundMortgageOut;
	/**
	 * 货币质押余额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double FundMortgageAvailable;
	/**
	 * 可质押货币金额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double MortgageableFund;
	/**
	 * 特殊产品占用保证金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double SpecProductMargin;
	/**
	 * 特殊产品冻结保证金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double SpecProductFrozenMargin;
	/**
	 * 特殊产品手续费<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double SpecProductCommission;
	/**
	 * 特殊产品冻结手续费<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double SpecProductFrozenCommission;
	/**
	 * 特殊产品持仓盈亏<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double SpecProductPositionProfit;
	/**
	 * 特殊产品平仓盈亏<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double SpecProductCloseProfit;
	/**
	 * 根据持仓盈亏算法计算的特殊产品持仓盈亏<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double SpecProductPositionProfitByAlg;
	/**
	 * 特殊产品交易所保证金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double SpecProductExchangeMargin;
	/**
	 * 期权平仓盈亏<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double OptionCloseProfit;
	/**
	 * 期权市值<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double OptionValue;
	public CThostFtdcSyncingTradingAccountField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "AccountID", "PreMortgage", "PreCredit", "PreDeposit", "PreBalance", "PreMargin", "InterestBase", "Interest", "Deposit", "Withdraw", "FrozenMargin", "FrozenCash", "FrozenCommission", "CurrMargin", "CashIn", "Commission", "CloseProfit", "PositionProfit", "Balance", "Available", "WithdrawQuota", "Reserve", "TradingDay", "SettlementID", "Credit", "Mortgage", "ExchangeMargin", "DeliveryMargin", "ExchangeDeliveryMargin", "ReserveBalance", "CurrencyID", "PreFundMortgageIn", "PreFundMortgageOut", "FundMortgageIn", "FundMortgageOut", "FundMortgageAvailable", "MortgageableFund", "SpecProductMargin", "SpecProductFrozenMargin", "SpecProductCommission", "SpecProductFrozenCommission", "SpecProductPositionProfit", "SpecProductCloseProfit", "SpecProductPositionProfitByAlg", "SpecProductExchangeMargin", "OptionCloseProfit", "OptionValue");
	}
	public static class ByReference extends CThostFtdcSyncingTradingAccountField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcSyncingTradingAccountField implements Structure.ByValue {
		
	};
}
