package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 根据价格查询最大报单数量<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:4894</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcQueryMaxOrderVolumeWithPriceField extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	public byte[] InvestorID = new byte[13];
	/**
	 * 合约代码<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	public byte[] InstrumentID = new byte[31];
	/**
	 * 买卖方向<br>
	 * C type : TThostFtdcDirectionType
	 */
	public byte Direction;
	/**
	 * 开平标志<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	public byte OffsetFlag;
	/**
	 * 投机套保标志<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	public byte HedgeFlag;
	/**
	 * 最大允许报单数量<br>
	 * C type : TThostFtdcVolumeType
	 */
	public int MaxVolume;
	/**
	 * 报单价格<br>
	 * C type : TThostFtdcPriceType
	 */
	public double Price;
	public CThostFtdcQueryMaxOrderVolumeWithPriceField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "InvestorID", "InstrumentID", "Direction", "OffsetFlag", "HedgeFlag", "MaxVolume", "Price");
	}
	/**
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param InvestorID 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType<br>
	 * @param InstrumentID 合约代码<br>
	 * C type : TThostFtdcInstrumentIDType<br>
	 * @param Direction 买卖方向<br>
	 * C type : TThostFtdcDirectionType<br>
	 * @param OffsetFlag 开平标志<br>
	 * C type : TThostFtdcOffsetFlagType<br>
	 * @param HedgeFlag 投机套保标志<br>
	 * C type : TThostFtdcHedgeFlagType<br>
	 * @param MaxVolume 最大允许报单数量<br>
	 * C type : TThostFtdcVolumeType<br>
	 * @param Price 报单价格<br>
	 * C type : TThostFtdcPriceType
	 */
	public CThostFtdcQueryMaxOrderVolumeWithPriceField(byte BrokerID[], byte InvestorID[], byte InstrumentID[], byte Direction, byte OffsetFlag, byte HedgeFlag, int MaxVolume, double Price) {
		super();
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		if ((InvestorID.length != this.InvestorID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.InvestorID = InvestorID;
		if ((InstrumentID.length != this.InstrumentID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.InstrumentID = InstrumentID;
		this.Direction = Direction;
		this.OffsetFlag = OffsetFlag;
		this.HedgeFlag = HedgeFlag;
		this.MaxVolume = MaxVolume;
		this.Price = Price;
	}
	public static class ByReference extends CThostFtdcQueryMaxOrderVolumeWithPriceField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcQueryMaxOrderVolumeWithPriceField implements Structure.ByValue {
		
	};
}
