package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 合约保证金率调整<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:1003</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcInstrumentMarginRateAdjustField extends Structure {
	/**
	 * 合约代码<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	public byte[] InstrumentID = new byte[31];
	/**
	 * 投资者范围<br>
	 * C type : TThostFtdcInvestorRangeType
	 */
	public byte InvestorRange;
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	public byte[] InvestorID = new byte[13];
	/**
	 * 投机套保标志<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	public byte HedgeFlag;
	/**
	 * 多头保证金率<br>
	 * C type : TThostFtdcRatioType
	 */
	public double LongMarginRatioByMoney;
	/**
	 * 多头保证金费<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double LongMarginRatioByVolume;
	/**
	 * 空头保证金率<br>
	 * C type : TThostFtdcRatioType
	 */
	public double ShortMarginRatioByMoney;
	/**
	 * 空头保证金费<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double ShortMarginRatioByVolume;
	/**
	 * 是否相对交易所收取<br>
	 * C type : TThostFtdcBoolType
	 */
	public int IsRelative;
	public CThostFtdcInstrumentMarginRateAdjustField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("InstrumentID", "InvestorRange", "BrokerID", "InvestorID", "HedgeFlag", "LongMarginRatioByMoney", "LongMarginRatioByVolume", "ShortMarginRatioByMoney", "ShortMarginRatioByVolume", "IsRelative");
	}
	public static class ByReference extends CThostFtdcInstrumentMarginRateAdjustField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcInstrumentMarginRateAdjustField implements Structure.ByValue {
		
	};
}
