package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 行情静态属性<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:3720</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcMarketDataStaticField extends Structure {
	/**
	 * 今开盘<br>
	 * C type : TThostFtdcPriceType
	 */
	public double OpenPrice;
	/**
	 * 最高价<br>
	 * C type : TThostFtdcPriceType
	 */
	public double HighestPrice;
	/**
	 * 最低价<br>
	 * C type : TThostFtdcPriceType
	 */
	public double LowestPrice;
	/**
	 * 今收盘<br>
	 * C type : TThostFtdcPriceType
	 */
	public double ClosePrice;
	/**
	 * 涨停板价<br>
	 * C type : TThostFtdcPriceType
	 */
	public double UpperLimitPrice;
	/**
	 * 跌停板价<br>
	 * C type : TThostFtdcPriceType
	 */
	public double LowerLimitPrice;
	/**
	 * 本次结算价<br>
	 * C type : TThostFtdcPriceType
	 */
	public double SettlementPrice;
	/**
	 * 今虚实度<br>
	 * C type : TThostFtdcRatioType
	 */
	public double CurrDelta;
	public CThostFtdcMarketDataStaticField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("OpenPrice", "HighestPrice", "LowestPrice", "ClosePrice", "UpperLimitPrice", "LowerLimitPrice", "SettlementPrice", "CurrDelta");
	}
	/**
	 * @param OpenPrice 今开盘<br>
	 * C type : TThostFtdcPriceType<br>
	 * @param HighestPrice 最高价<br>
	 * C type : TThostFtdcPriceType<br>
	 * @param LowestPrice 最低价<br>
	 * C type : TThostFtdcPriceType<br>
	 * @param ClosePrice 今收盘<br>
	 * C type : TThostFtdcPriceType<br>
	 * @param UpperLimitPrice 涨停板价<br>
	 * C type : TThostFtdcPriceType<br>
	 * @param LowerLimitPrice 跌停板价<br>
	 * C type : TThostFtdcPriceType<br>
	 * @param SettlementPrice 本次结算价<br>
	 * C type : TThostFtdcPriceType<br>
	 * @param CurrDelta 今虚实度<br>
	 * C type : TThostFtdcRatioType
	 */
	public CThostFtdcMarketDataStaticField(double OpenPrice, double HighestPrice, double LowestPrice, double ClosePrice, double UpperLimitPrice, double LowerLimitPrice, double SettlementPrice, double CurrDelta) {
		super();
		this.OpenPrice = OpenPrice;
		this.HighestPrice = HighestPrice;
		this.LowestPrice = LowestPrice;
		this.ClosePrice = ClosePrice;
		this.UpperLimitPrice = UpperLimitPrice;
		this.LowerLimitPrice = LowerLimitPrice;
		this.SettlementPrice = SettlementPrice;
		this.CurrDelta = CurrDelta;
	}
	public static class ByReference extends CThostFtdcMarketDataStaticField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcMarketDataStaticField implements Structure.ByValue {
		
	};
}
