package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 登录信息<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:1175</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcLogoutAllField extends Structure {
	/**
	 * 前置编号<br>
	 * C type : TThostFtdcFrontIDType
	 */
	public int FrontID;
	/**
	 * 会话编号<br>
	 * C type : TThostFtdcSessionIDType
	 */
	public int SessionID;
	/**
	 * 系统名称<br>
	 * C type : TThostFtdcSystemNameType
	 */
	public byte[] SystemName = new byte[41];
	public CThostFtdcLogoutAllField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("FrontID", "SessionID", "SystemName");
	}
	/**
	 * @param FrontID 前置编号<br>
	 * C type : TThostFtdcFrontIDType<br>
	 * @param SessionID 会话编号<br>
	 * C type : TThostFtdcSessionIDType<br>
	 * @param SystemName 系统名称<br>
	 * C type : TThostFtdcSystemNameType
	 */
	public CThostFtdcLogoutAllField(int FrontID, int SessionID, byte SystemName[]) {
		super();
		this.FrontID = FrontID;
		this.SessionID = SessionID;
		if ((SystemName.length != this.SystemName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.SystemName = SystemName;
	}
	public static class ByReference extends CThostFtdcLogoutAllField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcLogoutAllField implements Structure.ByValue {
		
	};
}
