package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 货币质押同步<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:1826</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcSyncFundMortgageField extends Structure {
	/**
	 * 货币质押流水号<br>
	 * C type : TThostFtdcDepositSeqNoType
	 */
	public byte[] MortgageSeqNo = new byte[15];
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	public byte[] InvestorID = new byte[13];
	/**
	 * 源币种<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	public byte[] FromCurrencyID = new byte[4];
	/**
	 * 质押金额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double MortgageAmount;
	/**
	 * 目标币种<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	public byte[] ToCurrencyID = new byte[4];
	public CThostFtdcSyncFundMortgageField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("MortgageSeqNo", "BrokerID", "InvestorID", "FromCurrencyID", "MortgageAmount", "ToCurrencyID");
	}
	/**
	 * @param MortgageSeqNo 货币质押流水号<br>
	 * C type : TThostFtdcDepositSeqNoType<br>
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param InvestorID 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType<br>
	 * @param FromCurrencyID 源币种<br>
	 * C type : TThostFtdcCurrencyIDType<br>
	 * @param MortgageAmount 质押金额<br>
	 * C type : TThostFtdcMoneyType<br>
	 * @param ToCurrencyID 目标币种<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	public CThostFtdcSyncFundMortgageField(byte MortgageSeqNo[], byte BrokerID[], byte InvestorID[], byte FromCurrencyID[], double MortgageAmount, byte ToCurrencyID[]) {
		super();
		if ((MortgageSeqNo.length != this.MortgageSeqNo.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.MortgageSeqNo = MortgageSeqNo;
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		if ((InvestorID.length != this.InvestorID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.InvestorID = InvestorID;
		if ((FromCurrencyID.length != this.FromCurrencyID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.FromCurrencyID = FromCurrencyID;
		this.MortgageAmount = MortgageAmount;
		if ((ToCurrencyID.length != this.ToCurrencyID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ToCurrencyID = ToCurrencyID;
	}
	public static class ByReference extends CThostFtdcSyncFundMortgageField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcSyncFundMortgageField implements Structure.ByValue {
		
	};
}
