package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 行情申买四、五属性<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:3793</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcMarketDataBid45Field extends Structure {
	/**
	 * 申买价四<br>
	 * C type : TThostFtdcPriceType
	 */
	public double BidPrice4;
	/**
	 * 申买量四<br>
	 * C type : TThostFtdcVolumeType
	 */
	public int BidVolume4;
	/**
	 * 申买价五<br>
	 * C type : TThostFtdcPriceType
	 */
	public double BidPrice5;
	/**
	 * 申买量五<br>
	 * C type : TThostFtdcVolumeType
	 */
	public int BidVolume5;
	public CThostFtdcMarketDataBid45Field() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BidPrice4", "BidVolume4", "BidPrice5", "BidVolume5");
	}
	/**
	 * @param BidPrice4 申买价四<br>
	 * C type : TThostFtdcPriceType<br>
	 * @param BidVolume4 申买量四<br>
	 * C type : TThostFtdcVolumeType<br>
	 * @param BidPrice5 申买价五<br>
	 * C type : TThostFtdcPriceType<br>
	 * @param BidVolume5 申买量五<br>
	 * C type : TThostFtdcVolumeType
	 */
	public CThostFtdcMarketDataBid45Field(double BidPrice4, int BidVolume4, double BidPrice5, int BidVolume5) {
		super();
		this.BidPrice4 = BidPrice4;
		this.BidVolume4 = BidVolume4;
		this.BidPrice5 = BidPrice5;
		this.BidVolume5 = BidVolume5;
	}
	public static class ByReference extends CThostFtdcMarketDataBid45Field implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcMarketDataBid45Field implements Structure.ByValue {
		
	};
}
