package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 资金账户口令变更域<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:4146</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcTradingAccountPasswordUpdateV1Field extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	public byte[] InvestorID = new byte[13];
	/**
	 * 原来的口令<br>
	 * C type : TThostFtdcPasswordType
	 */
	public byte[] OldPassword = new byte[41];
	/**
	 * 新的口令<br>
	 * C type : TThostFtdcPasswordType
	 */
	public byte[] NewPassword = new byte[41];
	public CThostFtdcTradingAccountPasswordUpdateV1Field() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "InvestorID", "OldPassword", "NewPassword");
	}
	/**
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param InvestorID 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType<br>
	 * @param OldPassword 原来的口令<br>
	 * C type : TThostFtdcPasswordType<br>
	 * @param NewPassword 新的口令<br>
	 * C type : TThostFtdcPasswordType
	 */
	public CThostFtdcTradingAccountPasswordUpdateV1Field(byte BrokerID[], byte InvestorID[], byte OldPassword[], byte NewPassword[]) {
		super();
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		if ((InvestorID.length != this.InvestorID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.InvestorID = InvestorID;
		if ((OldPassword.length != this.OldPassword.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.OldPassword = OldPassword;
		if ((NewPassword.length != this.NewPassword.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.NewPassword = NewPassword;
	}
	public static class ByReference extends CThostFtdcTradingAccountPasswordUpdateV1Field implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcTradingAccountPasswordUpdateV1Field implements Structure.ByValue {
		
	};
}
