package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 保证金监管系统经纪公司资金账户密钥<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:5039</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcCFMMCTradingAccountKeyField extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 经纪公司统一编码<br>
	 * C type : TThostFtdcParticipantIDType
	 */
	public byte[] ParticipantID = new byte[11];
	/**
	 * 投资者帐号<br>
	 * C type : TThostFtdcAccountIDType
	 */
	public byte[] AccountID = new byte[13];
	/**
	 * 密钥编号<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	public int KeyID;
	/**
	 * 动态密钥<br>
	 * C type : TThostFtdcCFMMCKeyType
	 */
	public byte[] CurrentKey = new byte[21];
	public CThostFtdcCFMMCTradingAccountKeyField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "ParticipantID", "AccountID", "KeyID", "CurrentKey");
	}
	/**
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param ParticipantID 经纪公司统一编码<br>
	 * C type : TThostFtdcParticipantIDType<br>
	 * @param AccountID 投资者帐号<br>
	 * C type : TThostFtdcAccountIDType<br>
	 * @param KeyID 密钥编号<br>
	 * C type : TThostFtdcSequenceNoType<br>
	 * @param CurrentKey 动态密钥<br>
	 * C type : TThostFtdcCFMMCKeyType
	 */
	public CThostFtdcCFMMCTradingAccountKeyField(byte BrokerID[], byte ParticipantID[], byte AccountID[], int KeyID, byte CurrentKey[]) {
		super();
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		if ((ParticipantID.length != this.ParticipantID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ParticipantID = ParticipantID;
		if ((AccountID.length != this.AccountID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.AccountID = AccountID;
		this.KeyID = KeyID;
		if ((CurrentKey.length != this.CurrentKey.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.CurrentKey = CurrentKey;
	}
	public static class ByReference extends CThostFtdcCFMMCTradingAccountKeyField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcCFMMCTradingAccountKeyField implements Structure.ByValue {
		
	};
}
