package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 查询签约银行请求<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:4290</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcQryContractBankField extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 银行代码<br>
	 * C type : TThostFtdcBankIDType
	 */
	public byte[] BankID = new byte[4];
	/**
	 * 银行分中心代码<br>
	 * C type : TThostFtdcBankBrchIDType
	 */
	public byte[] BankBrchID = new byte[5];
	public CThostFtdcQryContractBankField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "BankID", "BankBrchID");
	}
	/**
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param BankID 银行代码<br>
	 * C type : TThostFtdcBankIDType<br>
	 * @param BankBrchID 银行分中心代码<br>
	 * C type : TThostFtdcBankBrchIDType
	 */
	public CThostFtdcQryContractBankField(byte BrokerID[], byte BankID[], byte BankBrchID[]) {
		super();
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		if ((BankID.length != this.BankID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BankID = BankID;
		if ((BankBrchID.length != this.BankBrchID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BankBrchID = BankBrchID;
	}
	public static class ByReference extends CThostFtdcQryContractBankField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcQryContractBankField implements Structure.ByValue {
		
	};
}
