package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 查询转帐银行<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:3917</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcQryTransferBankField extends Structure {
	/**
	 * 银行代码<br>
	 * C type : TThostFtdcBankIDType
	 */
	public byte[] BankID = new byte[4];
	/**
	 * 银行分中心代码<br>
	 * C type : TThostFtdcBankBrchIDType
	 */
	public byte[] BankBrchID = new byte[5];
	public CThostFtdcQryTransferBankField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BankID", "BankBrchID");
	}
	/**
	 * @param BankID 银行代码<br>
	 * C type : TThostFtdcBankIDType<br>
	 * @param BankBrchID 银行分中心代码<br>
	 * C type : TThostFtdcBankBrchIDType
	 */
	public CThostFtdcQryTransferBankField(byte BankID[], byte BankBrchID[]) {
		super();
		if ((BankID.length != this.BankID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BankID = BankID;
		if ((BankBrchID.length != this.BankBrchID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BankBrchID = BankBrchID;
	}
	public static class ByReference extends CThostFtdcQryTransferBankField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcQryTransferBankField implements Structure.ByValue {
		
	};
}
