package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 用户事件通知<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:4591</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcTradingNoticeField extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 投资者范围<br>
	 * C type : TThostFtdcInvestorRangeType
	 */
	public byte InvestorRange;
	/**
	 * 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	public byte[] InvestorID = new byte[13];
	/**
	 * 序列系列号<br>
	 * C type : TThostFtdcSequenceSeriesType
	 */
	public short SequenceSeries;
	/**
	 * 用户代码<br>
	 * C type : TThostFtdcUserIDType
	 */
	public byte[] UserID = new byte[16];
	/**
	 * 发送时间<br>
	 * C type : TThostFtdcTimeType
	 */
	public byte[] SendTime = new byte[9];
	/**
	 * 序列号<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	public int SequenceNo;
	/**
	 * 消息正文<br>
	 * C type : TThostFtdcContentType
	 */
	public byte[] FieldContent = new byte[501];
	public CThostFtdcTradingNoticeField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "InvestorRange", "InvestorID", "SequenceSeries", "UserID", "SendTime", "SequenceNo", "FieldContent");
	}
	/**
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param InvestorRange 投资者范围<br>
	 * C type : TThostFtdcInvestorRangeType<br>
	 * @param InvestorID 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType<br>
	 * @param SequenceSeries 序列系列号<br>
	 * C type : TThostFtdcSequenceSeriesType<br>
	 * @param UserID 用户代码<br>
	 * C type : TThostFtdcUserIDType<br>
	 * @param SendTime 发送时间<br>
	 * C type : TThostFtdcTimeType<br>
	 * @param SequenceNo 序列号<br>
	 * C type : TThostFtdcSequenceNoType<br>
	 * @param FieldContent 消息正文<br>
	 * C type : TThostFtdcContentType
	 */
	public CThostFtdcTradingNoticeField(byte BrokerID[], byte InvestorRange, byte InvestorID[], short SequenceSeries, byte UserID[], byte SendTime[], int SequenceNo, byte FieldContent[]) {
		super();
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		this.InvestorRange = InvestorRange;
		if ((InvestorID.length != this.InvestorID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.InvestorID = InvestorID;
		this.SequenceSeries = SequenceSeries;
		if ((UserID.length != this.UserID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.UserID = UserID;
		if ((SendTime.length != this.SendTime.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.SendTime = SendTime;
		this.SequenceNo = SequenceNo;
		if ((FieldContent.length != this.FieldContent.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.FieldContent = FieldContent;
	}
	public static class ByReference extends CThostFtdcTradingNoticeField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcTradingNoticeField implements Structure.ByValue {
		
	};
}
