package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 手工同步用户动态令牌<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:5084</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcManualSyncBrokerUserOTPField extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 用户代码<br>
	 * C type : TThostFtdcUserIDType
	 */
	public byte[] UserID = new byte[16];
	/**
	 * 动态令牌类型<br>
	 * C type : TThostFtdcOTPTypeType
	 */
	public byte OTPType;
	/**
	 * 第一个动态密码<br>
	 * C type : TThostFtdcPasswordType
	 */
	public byte[] FirstOTP = new byte[41];
	/**
	 * 第二个动态密码<br>
	 * C type : TThostFtdcPasswordType
	 */
	public byte[] SecondOTP = new byte[41];
	public CThostFtdcManualSyncBrokerUserOTPField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "UserID", "OTPType", "FirstOTP", "SecondOTP");
	}
	/**
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param UserID 用户代码<br>
	 * C type : TThostFtdcUserIDType<br>
	 * @param OTPType 动态令牌类型<br>
	 * C type : TThostFtdcOTPTypeType<br>
	 * @param FirstOTP 第一个动态密码<br>
	 * C type : TThostFtdcPasswordType<br>
	 * @param SecondOTP 第二个动态密码<br>
	 * C type : TThostFtdcPasswordType
	 */
	public CThostFtdcManualSyncBrokerUserOTPField(byte BrokerID[], byte UserID[], byte OTPType, byte FirstOTP[], byte SecondOTP[]) {
		super();
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		if ((UserID.length != this.UserID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.UserID = UserID;
		this.OTPType = OTPType;
		if ((FirstOTP.length != this.FirstOTP.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.FirstOTP = FirstOTP;
		if ((SecondOTP.length != this.SecondOTP.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.SecondOTP = SecondOTP;
	}
	public static class ByReference extends CThostFtdcManualSyncBrokerUserOTPField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcManualSyncBrokerUserOTPField implements Structure.ByValue {
		
	};
}
