package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 行情申买二、三属性<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:3767</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcMarketDataBid23Field extends Structure {
	/**
	 * 申买价二<br>
	 * C type : TThostFtdcPriceType
	 */
	public double BidPrice2;
	/**
	 * 申买量二<br>
	 * C type : TThostFtdcVolumeType
	 */
	public int BidVolume2;
	/**
	 * 申买价三<br>
	 * C type : TThostFtdcPriceType
	 */
	public double BidPrice3;
	/**
	 * 申买量三<br>
	 * C type : TThostFtdcVolumeType
	 */
	public int BidVolume3;
	public CThostFtdcMarketDataBid23Field() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BidPrice2", "BidVolume2", "BidPrice3", "BidVolume3");
	}
	/**
	 * @param BidPrice2 申买价二<br>
	 * C type : TThostFtdcPriceType<br>
	 * @param BidVolume2 申买量二<br>
	 * C type : TThostFtdcVolumeType<br>
	 * @param BidPrice3 申买价三<br>
	 * C type : TThostFtdcPriceType<br>
	 * @param BidVolume3 申买量三<br>
	 * C type : TThostFtdcVolumeType
	 */
	public CThostFtdcMarketDataBid23Field(double BidPrice2, int BidVolume2, double BidPrice3, int BidVolume3) {
		super();
		this.BidPrice2 = BidPrice2;
		this.BidVolume2 = BidVolume2;
		this.BidPrice3 = BidPrice3;
		this.BidVolume3 = BidVolume3;
	}
	public static class ByReference extends CThostFtdcMarketDataBid23Field implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcMarketDataBid23Field implements Structure.ByValue {
		
	};
}
