package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 合约状态<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:3846</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcInstrumentStatusField extends Structure {
	/**
	 * 交易所代码<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	public byte[] ExchangeID = new byte[9];
	/**
	 * 合约在交易所的代码<br>
	 * C type : TThostFtdcExchangeInstIDType
	 */
	public byte[] ExchangeInstID = new byte[31];
	/**
	 * 结算组代码<br>
	 * C type : TThostFtdcSettlementGroupIDType
	 */
	public byte[] SettlementGroupID = new byte[9];
	/**
	 * 合约代码<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	public byte[] InstrumentID = new byte[31];
	/**
	 * 合约交易状态<br>
	 * C type : TThostFtdcInstrumentStatusType
	 */
	public byte InstrumentStatus;
	/**
	 * 交易阶段编号<br>
	 * C type : TThostFtdcTradingSegmentSNType
	 */
	public int TradingSegmentSN;
	/**
	 * 进入本状态时间<br>
	 * C type : TThostFtdcTimeType
	 */
	public byte[] EnterTime = new byte[9];
	/**
	 * 进入本状态原因<br>
	 * C type : TThostFtdcInstStatusEnterReasonType
	 */
	public byte EnterReason;
	public CThostFtdcInstrumentStatusField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("ExchangeID", "ExchangeInstID", "SettlementGroupID", "InstrumentID", "InstrumentStatus", "TradingSegmentSN", "EnterTime", "EnterReason");
	}
	/**
	 * @param ExchangeID 交易所代码<br>
	 * C type : TThostFtdcExchangeIDType<br>
	 * @param ExchangeInstID 合约在交易所的代码<br>
	 * C type : TThostFtdcExchangeInstIDType<br>
	 * @param SettlementGroupID 结算组代码<br>
	 * C type : TThostFtdcSettlementGroupIDType<br>
	 * @param InstrumentID 合约代码<br>
	 * C type : TThostFtdcInstrumentIDType<br>
	 * @param InstrumentStatus 合约交易状态<br>
	 * C type : TThostFtdcInstrumentStatusType<br>
	 * @param TradingSegmentSN 交易阶段编号<br>
	 * C type : TThostFtdcTradingSegmentSNType<br>
	 * @param EnterTime 进入本状态时间<br>
	 * C type : TThostFtdcTimeType<br>
	 * @param EnterReason 进入本状态原因<br>
	 * C type : TThostFtdcInstStatusEnterReasonType
	 */
	public CThostFtdcInstrumentStatusField(byte ExchangeID[], byte ExchangeInstID[], byte SettlementGroupID[], byte InstrumentID[], byte InstrumentStatus, int TradingSegmentSN, byte EnterTime[], byte EnterReason) {
		super();
		if ((ExchangeID.length != this.ExchangeID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ExchangeID = ExchangeID;
		if ((ExchangeInstID.length != this.ExchangeInstID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ExchangeInstID = ExchangeInstID;
		if ((SettlementGroupID.length != this.SettlementGroupID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.SettlementGroupID = SettlementGroupID;
		if ((InstrumentID.length != this.InstrumentID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.InstrumentID = InstrumentID;
		this.InstrumentStatus = InstrumentStatus;
		this.TradingSegmentSN = TradingSegmentSN;
		if ((EnterTime.length != this.EnterTime.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.EnterTime = EnterTime;
		this.EnterReason = EnterReason;
	}
	public static class ByReference extends CThostFtdcInstrumentStatusField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcInstrumentStatusField implements Structure.ByValue {
		
	};
}
