package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 出入金同步<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:1809</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcSyncDepositField extends Structure {
	/**
	 * 出入金流水号<br>
	 * C type : TThostFtdcDepositSeqNoType
	 */
	public byte[] DepositSeqNo = new byte[15];
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	public byte[] InvestorID = new byte[13];
	/**
	 * 入金金额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double Deposit;
	/**
	 * 是否强制进行<br>
	 * C type : TThostFtdcBoolType
	 */
	public int IsForce;
	/**
	 * 币种代码<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	public byte[] CurrencyID = new byte[4];
	public CThostFtdcSyncDepositField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("DepositSeqNo", "BrokerID", "InvestorID", "Deposit", "IsForce", "CurrencyID");
	}
	/**
	 * @param DepositSeqNo 出入金流水号<br>
	 * C type : TThostFtdcDepositSeqNoType<br>
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param InvestorID 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType<br>
	 * @param Deposit 入金金额<br>
	 * C type : TThostFtdcMoneyType<br>
	 * @param IsForce 是否强制进行<br>
	 * C type : TThostFtdcBoolType<br>
	 * @param CurrencyID 币种代码<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	public CThostFtdcSyncDepositField(byte DepositSeqNo[], byte BrokerID[], byte InvestorID[], double Deposit, int IsForce, byte CurrencyID[]) {
		super();
		if ((DepositSeqNo.length != this.DepositSeqNo.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.DepositSeqNo = DepositSeqNo;
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		if ((InvestorID.length != this.InvestorID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.InvestorID = InvestorID;
		this.Deposit = Deposit;
		this.IsForce = IsForce;
		if ((CurrencyID.length != this.CurrencyID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.CurrencyID = CurrencyID;
	}
	public static class ByReference extends CThostFtdcSyncDepositField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcSyncDepositField implements Structure.ByValue {
		
	};
}
