package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 当前时间<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:1106</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcCurrentTimeField extends Structure {
	/**
	 * 当前日期<br>
	 * C type : TThostFtdcDateType
	 */
	public byte[] CurrDate = new byte[9];
	/**
	 * 当前时间<br>
	 * C type : TThostFtdcTimeType
	 */
	public byte[] CurrTime = new byte[9];
	/**
	 * 当前时间（毫秒）<br>
	 * C type : TThostFtdcMillisecType
	 */
	public int CurrMillisec;
	/**
	 * 业务日期<br>
	 * C type : TThostFtdcDateType
	 */
	public byte[] ActionDay = new byte[9];
	public CThostFtdcCurrentTimeField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("CurrDate", "CurrTime", "CurrMillisec", "ActionDay");
	}
	/**
	 * @param CurrDate 当前日期<br>
	 * C type : TThostFtdcDateType<br>
	 * @param CurrTime 当前时间<br>
	 * C type : TThostFtdcTimeType<br>
	 * @param CurrMillisec 当前时间（毫秒）<br>
	 * C type : TThostFtdcMillisecType<br>
	 * @param ActionDay 业务日期<br>
	 * C type : TThostFtdcDateType
	 */
	public CThostFtdcCurrentTimeField(byte CurrDate[], byte CurrTime[], int CurrMillisec, byte ActionDay[]) {
		super();
		if ((CurrDate.length != this.CurrDate.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.CurrDate = CurrDate;
		if ((CurrTime.length != this.CurrTime.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.CurrTime = CurrTime;
		this.CurrMillisec = CurrMillisec;
		if ((ActionDay.length != this.ActionDay.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ActionDay = ActionDay;
	}
	public static class ByReference extends CThostFtdcCurrentTimeField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcCurrentTimeField implements Structure.ByValue {
		
	};
}
