package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 行情申卖二、三属性<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:3780</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcMarketDataAsk23Field extends Structure {
	/**
	 * 申卖价二<br>
	 * C type : TThostFtdcPriceType
	 */
	public double AskPrice2;
	/**
	 * 申卖量二<br>
	 * C type : TThostFtdcVolumeType
	 */
	public int AskVolume2;
	/**
	 * 申卖价三<br>
	 * C type : TThostFtdcPriceType
	 */
	public double AskPrice3;
	/**
	 * 申卖量三<br>
	 * C type : TThostFtdcVolumeType
	 */
	public int AskVolume3;
	public CThostFtdcMarketDataAsk23Field() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("AskPrice2", "AskVolume2", "AskPrice3", "AskVolume3");
	}
	/**
	 * @param AskPrice2 申卖价二<br>
	 * C type : TThostFtdcPriceType<br>
	 * @param AskVolume2 申卖量二<br>
	 * C type : TThostFtdcVolumeType<br>
	 * @param AskPrice3 申卖价三<br>
	 * C type : TThostFtdcPriceType<br>
	 * @param AskVolume3 申卖量三<br>
	 * C type : TThostFtdcVolumeType
	 */
	public CThostFtdcMarketDataAsk23Field(double AskPrice2, int AskVolume2, double AskPrice3, int AskVolume3) {
		super();
		this.AskPrice2 = AskPrice2;
		this.AskVolume2 = AskVolume2;
		this.AskPrice3 = AskPrice3;
		this.AskVolume3 = AskVolume3;
	}
	public static class ByReference extends CThostFtdcMarketDataAsk23Field implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcMarketDataAsk23Field implements Structure.ByValue {
		
	};
}
