package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 信息分发<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:9</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcDisseminationField extends Structure {
	/**
	 * 序列系列号<br>
	 * C type : TThostFtdcSequenceSeriesType
	 */
	public short SequenceSeries;
	/**
	 * 序列号<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	public int SequenceNo;
	public CThostFtdcDisseminationField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("SequenceSeries", "SequenceNo");
	}
	/**
	 * @param SequenceSeries 序列系列号<br>
	 * C type : TThostFtdcSequenceSeriesType<br>
	 * @param SequenceNo 序列号<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	public CThostFtdcDisseminationField(short SequenceSeries, int SequenceNo) {
		super();
		this.SequenceSeries = SequenceSeries;
		this.SequenceNo = SequenceNo;
	}
	public static class ByReference extends CThostFtdcDisseminationField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcDisseminationField implements Structure.ByValue {
		
	};
}
