package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 删除预埋单<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:4491</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcRemoveParkedOrderField extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	public byte[] InvestorID = new byte[13];
	/**
	 * 预埋报单编号<br>
	 * C type : TThostFtdcParkedOrderIDType
	 */
	public byte[] ParkedOrderID = new byte[13];
	public CThostFtdcRemoveParkedOrderField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "InvestorID", "ParkedOrderID");
	}
	/**
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param InvestorID 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType<br>
	 * @param ParkedOrderID 预埋报单编号<br>
	 * C type : TThostFtdcParkedOrderIDType
	 */
	public CThostFtdcRemoveParkedOrderField(byte BrokerID[], byte InvestorID[], byte ParkedOrderID[]) {
		super();
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		if ((InvestorID.length != this.InvestorID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.InvestorID = InvestorID;
		if ((ParkedOrderID.length != this.ParkedOrderID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ParkedOrderID = ParkedOrderID;
	}
	public static class ByReference extends CThostFtdcRemoveParkedOrderField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcRemoveParkedOrderField implements Structure.ByValue {
		
	};
}
