package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 行情更新时间属性<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:3819</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcMarketDataUpdateTimeField extends Structure {
	/**
	 * 合约代码<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	public byte[] InstrumentID = new byte[31];
	/**
	 * 最后修改时间<br>
	 * C type : TThostFtdcTimeType
	 */
	public byte[] UpdateTime = new byte[9];
	/**
	 * 最后修改毫秒<br>
	 * C type : TThostFtdcMillisecType
	 */
	public int UpdateMillisec;
	/**
	 * 业务日期<br>
	 * C type : TThostFtdcDateType
	 */
	public byte[] ActionDay = new byte[9];
	public CThostFtdcMarketDataUpdateTimeField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("InstrumentID", "UpdateTime", "UpdateMillisec", "ActionDay");
	}
	/**
	 * @param InstrumentID 合约代码<br>
	 * C type : TThostFtdcInstrumentIDType<br>
	 * @param UpdateTime 最后修改时间<br>
	 * C type : TThostFtdcTimeType<br>
	 * @param UpdateMillisec 最后修改毫秒<br>
	 * C type : TThostFtdcMillisecType<br>
	 * @param ActionDay 业务日期<br>
	 * C type : TThostFtdcDateType
	 */
	public CThostFtdcMarketDataUpdateTimeField(byte InstrumentID[], byte UpdateTime[], int UpdateMillisec, byte ActionDay[]) {
		super();
		if ((InstrumentID.length != this.InstrumentID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.InstrumentID = InstrumentID;
		if ((UpdateTime.length != this.UpdateTime.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.UpdateTime = UpdateTime;
		this.UpdateMillisec = UpdateMillisec;
		if ((ActionDay.length != this.ActionDay.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ActionDay = ActionDay;
	}
	public static class ByReference extends CThostFtdcMarketDataUpdateTimeField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcMarketDataUpdateTimeField implements Structure.ByValue {
		
	};
}
