package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 投资者品种/跨品种保证金<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:5186</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcInvestorProductGroupMarginField extends Structure {
	/**
	 * 品种/跨品种标示<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	public byte[] ProductGroupID = new byte[31];
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	public byte[] InvestorID = new byte[13];
	/**
	 * 交易日<br>
	 * C type : TThostFtdcDateType
	 */
	public byte[] TradingDay = new byte[9];
	/**
	 * 结算编号<br>
	 * C type : TThostFtdcSettlementIDType
	 */
	public int SettlementID;
	/**
	 * 冻结的保证金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double FrozenMargin;
	/**
	 * 多头冻结的保证金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double LongFrozenMargin;
	/**
	 * 空头冻结的保证金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double ShortFrozenMargin;
	/**
	 * 占用的保证金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double UseMargin;
	/**
	 * 多头保证金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double LongUseMargin;
	/**
	 * 空头保证金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double ShortUseMargin;
	/**
	 * 交易所保证金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double ExchMargin;
	/**
	 * 交易所多头保证金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double LongExchMargin;
	/**
	 * 交易所空头保证金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double ShortExchMargin;
	/**
	 * 平仓盈亏<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double CloseProfit;
	/**
	 * 冻结的手续费<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double FrozenCommission;
	/**
	 * 手续费<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double Commission;
	/**
	 * 冻结的资金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double FrozenCash;
	/**
	 * 资金差额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double CashIn;
	/**
	 * 持仓盈亏<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double PositionProfit;
	/**
	 * 折抵总金额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double OffsetAmount;
	/**
	 * 多头折抵总金额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double LongOffsetAmount;
	/**
	 * 空头折抵总金额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double ShortOffsetAmount;
	/**
	 * 交易所折抵总金额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double ExchOffsetAmount;
	/**
	 * 交易所多头折抵总金额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double LongExchOffsetAmount;
	/**
	 * 交易所空头折抵总金额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double ShortExchOffsetAmount;
	/**
	 * 投机套保标志<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	public byte HedgeFlag;
	public CThostFtdcInvestorProductGroupMarginField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("ProductGroupID", "BrokerID", "InvestorID", "TradingDay", "SettlementID", "FrozenMargin", "LongFrozenMargin", "ShortFrozenMargin", "UseMargin", "LongUseMargin", "ShortUseMargin", "ExchMargin", "LongExchMargin", "ShortExchMargin", "CloseProfit", "FrozenCommission", "Commission", "FrozenCash", "CashIn", "PositionProfit", "OffsetAmount", "LongOffsetAmount", "ShortOffsetAmount", "ExchOffsetAmount", "LongExchOffsetAmount", "ShortExchOffsetAmount", "HedgeFlag");
	}
	public static class ByReference extends CThostFtdcInvestorProductGroupMarginField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcInvestorProductGroupMarginField implements Structure.ByValue {
		
	};
}
