package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 行情最优价属性<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:3754</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcMarketDataBestPriceField extends Structure {
	/**
	 * 申买价一<br>
	 * C type : TThostFtdcPriceType
	 */
	public double BidPrice1;
	/**
	 * 申买量一<br>
	 * C type : TThostFtdcVolumeType
	 */
	public int BidVolume1;
	/**
	 * 申卖价一<br>
	 * C type : TThostFtdcPriceType
	 */
	public double AskPrice1;
	/**
	 * 申卖量一<br>
	 * C type : TThostFtdcVolumeType
	 */
	public int AskVolume1;
	public CThostFtdcMarketDataBestPriceField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BidPrice1", "BidVolume1", "AskPrice1", "AskVolume1");
	}
	/**
	 * @param BidPrice1 申买价一<br>
	 * C type : TThostFtdcPriceType<br>
	 * @param BidVolume1 申买量一<br>
	 * C type : TThostFtdcVolumeType<br>
	 * @param AskPrice1 申卖价一<br>
	 * C type : TThostFtdcPriceType<br>
	 * @param AskVolume1 申卖量一<br>
	 * C type : TThostFtdcVolumeType
	 */
	public CThostFtdcMarketDataBestPriceField(double BidPrice1, int BidVolume1, double AskPrice1, int AskVolume1) {
		super();
		this.BidPrice1 = BidPrice1;
		this.BidVolume1 = BidVolume1;
		this.AskPrice1 = AskPrice1;
		this.AskVolume1 = AskVolume1;
	}
	public static class ByReference extends CThostFtdcMarketDataBestPriceField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcMarketDataBestPriceField implements Structure.ByValue {
		
	};
}
