package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 经纪公司交易算法<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:4956</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcBrokerTradingAlgosField extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 交易所代码<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	public byte[] ExchangeID = new byte[9];
	/**
	 * 合约代码<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	public byte[] InstrumentID = new byte[31];
	/**
	 * 持仓处理算法编号<br>
	 * C type : TThostFtdcHandlePositionAlgoIDType
	 */
	public byte HandlePositionAlgoID;
	/**
	 * 寻找保证金率算法编号<br>
	 * C type : TThostFtdcFindMarginRateAlgoIDType
	 */
	public byte FindMarginRateAlgoID;
	/**
	 * 资金处理算法编号<br>
	 * C type : TThostFtdcHandleTradingAccountAlgoIDType
	 */
	public byte HandleTradingAccountAlgoID;
	public CThostFtdcBrokerTradingAlgosField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "ExchangeID", "InstrumentID", "HandlePositionAlgoID", "FindMarginRateAlgoID", "HandleTradingAccountAlgoID");
	}
	/**
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param ExchangeID 交易所代码<br>
	 * C type : TThostFtdcExchangeIDType<br>
	 * @param InstrumentID 合约代码<br>
	 * C type : TThostFtdcInstrumentIDType<br>
	 * @param HandlePositionAlgoID 持仓处理算法编号<br>
	 * C type : TThostFtdcHandlePositionAlgoIDType<br>
	 * @param FindMarginRateAlgoID 寻找保证金率算法编号<br>
	 * C type : TThostFtdcFindMarginRateAlgoIDType<br>
	 * @param HandleTradingAccountAlgoID 资金处理算法编号<br>
	 * C type : TThostFtdcHandleTradingAccountAlgoIDType
	 */
	public CThostFtdcBrokerTradingAlgosField(byte BrokerID[], byte ExchangeID[], byte InstrumentID[], byte HandlePositionAlgoID, byte FindMarginRateAlgoID, byte HandleTradingAccountAlgoID) {
		super();
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		if ((ExchangeID.length != this.ExchangeID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ExchangeID = ExchangeID;
		if ((InstrumentID.length != this.InstrumentID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.InstrumentID = InstrumentID;
		this.HandlePositionAlgoID = HandlePositionAlgoID;
		this.FindMarginRateAlgoID = FindMarginRateAlgoID;
		this.HandleTradingAccountAlgoID = HandleTradingAccountAlgoID;
	}
	public static class ByReference extends CThostFtdcBrokerTradingAlgosField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcBrokerTradingAlgosField implements Structure.ByValue {
		
	};
}
