package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 当前期权合约保证金调整系数<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:2565</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcOptionInstrMarginAdjustField extends Structure {
	/**
	 * 合约代码<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	public byte[] InstrumentID = new byte[31];
	/**
	 * 投资者范围<br>
	 * C type : TThostFtdcInvestorRangeType
	 */
	public byte InvestorRange;
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	public byte[] InvestorID = new byte[13];
	/**
	 * 投机空头保证金调整系数<br>
	 * C type : TThostFtdcRatioType
	 */
	public double SShortMarginRatioByMoney;
	/**
	 * 投机空头保证金调整系数<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double SShortMarginRatioByVolume;
	/**
	 * 保值空头保证金调整系数<br>
	 * C type : TThostFtdcRatioType
	 */
	public double HShortMarginRatioByMoney;
	/**
	 * 保值空头保证金调整系数<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double HShortMarginRatioByVolume;
	/**
	 * 套利空头保证金调整系数<br>
	 * C type : TThostFtdcRatioType
	 */
	public double AShortMarginRatioByMoney;
	/**
	 * 套利空头保证金调整系数<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double AShortMarginRatioByVolume;
	/**
	 * 是否跟随交易所收取<br>
	 * C type : TThostFtdcBoolType
	 */
	public int IsRelative;
	public CThostFtdcOptionInstrMarginAdjustField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("InstrumentID", "InvestorRange", "BrokerID", "InvestorID", "SShortMarginRatioByMoney", "SShortMarginRatioByVolume", "HShortMarginRatioByMoney", "HShortMarginRatioByVolume", "AShortMarginRatioByMoney", "AShortMarginRatioByVolume", "IsRelative");
	}
	public static class ByReference extends CThostFtdcOptionInstrMarginAdjustField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcOptionInstrMarginAdjustField implements Structure.ByValue {
		
	};
}
