package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 二级代理操作员银期权限<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:7269</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcSecAgentACIDMapField extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 用户代码<br>
	 * C type : TThostFtdcUserIDType
	 */
	public byte[] UserID = new byte[16];
	/**
	 * 资金账户<br>
	 * C type : TThostFtdcAccountIDType
	 */
	public byte[] AccountID = new byte[13];
	/**
	 * 币种<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	public byte[] CurrencyID = new byte[4];
	/**
	 * 境外中介机构资金帐号<br>
	 * C type : TThostFtdcAccountIDType
	 */
	public byte[] BrokerSecAgentID = new byte[13];
	public CThostFtdcSecAgentACIDMapField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "UserID", "AccountID", "CurrencyID", "BrokerSecAgentID");
	}
	/**
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param UserID 用户代码<br>
	 * C type : TThostFtdcUserIDType<br>
	 * @param AccountID 资金账户<br>
	 * C type : TThostFtdcAccountIDType<br>
	 * @param CurrencyID 币种<br>
	 * C type : TThostFtdcCurrencyIDType<br>
	 * @param BrokerSecAgentID 境外中介机构资金帐号<br>
	 * C type : TThostFtdcAccountIDType
	 */
	public CThostFtdcSecAgentACIDMapField(byte BrokerID[], byte UserID[], byte AccountID[], byte CurrencyID[], byte BrokerSecAgentID[]) {
		super();
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		if ((UserID.length != this.UserID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.UserID = UserID;
		if ((AccountID.length != this.AccountID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.AccountID = AccountID;
		if ((CurrencyID.length != this.CurrencyID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.CurrencyID = CurrencyID;
		if ((BrokerSecAgentID.length != this.BrokerSecAgentID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerSecAgentID = BrokerSecAgentID;
	}
	public static class ByReference extends CThostFtdcSecAgentACIDMapField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcSecAgentACIDMapField implements Structure.ByValue {
		
	};
}
