package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 管理用户功能权限<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:532</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcSuperUserFunctionField extends Structure {
	/**
	 * 用户代码<br>
	 * C type : TThostFtdcUserIDType
	 */
	public byte[] UserID = new byte[16];
	/**
	 * 功能代码<br>
	 * C type : TThostFtdcFunctionCodeType
	 */
	public byte FunctionCode;
	public CThostFtdcSuperUserFunctionField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("UserID", "FunctionCode");
	}
	/**
	 * @param UserID 用户代码<br>
	 * C type : TThostFtdcUserIDType<br>
	 * @param FunctionCode 功能代码<br>
	 * C type : TThostFtdcFunctionCodeType
	 */
	public CThostFtdcSuperUserFunctionField(byte UserID[], byte FunctionCode) {
		super();
		if ((UserID.length != this.UserID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.UserID = UserID;
		this.FunctionCode = FunctionCode;
	}
	public static class ByReference extends CThostFtdcSuperUserFunctionField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcSuperUserFunctionField implements Structure.ByValue {
		
	};
}
