package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 验证期货资金密码和客户信息<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:6486</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcVerifyFuturePasswordAndCustInfoField extends Structure {
	/**
	 * 客户姓名<br>
	 * C type : TThostFtdcIndividualNameType
	 */
	public byte[] CustomerName = new byte[51];
	/**
	 * 证件类型<br>
	 * C type : TThostFtdcIdCardTypeType
	 */
	public byte IdCardType;
	/**
	 * 证件号码<br>
	 * C type : TThostFtdcIdentifiedCardNoType
	 */
	public byte[] IdentifiedCardNo = new byte[51];
	/**
	 * 客户类型<br>
	 * C type : TThostFtdcCustTypeType
	 */
	public byte CustType;
	/**
	 * 投资者帐号<br>
	 * C type : TThostFtdcAccountIDType
	 */
	public byte[] AccountID = new byte[13];
	/**
	 * 期货密码<br>
	 * C type : TThostFtdcPasswordType
	 */
	public byte[] Password = new byte[41];
	/**
	 * 币种代码<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	public byte[] CurrencyID = new byte[4];
	public CThostFtdcVerifyFuturePasswordAndCustInfoField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("CustomerName", "IdCardType", "IdentifiedCardNo", "CustType", "AccountID", "Password", "CurrencyID");
	}
	/**
	 * @param CustomerName 客户姓名<br>
	 * C type : TThostFtdcIndividualNameType<br>
	 * @param IdCardType 证件类型<br>
	 * C type : TThostFtdcIdCardTypeType<br>
	 * @param IdentifiedCardNo 证件号码<br>
	 * C type : TThostFtdcIdentifiedCardNoType<br>
	 * @param CustType 客户类型<br>
	 * C type : TThostFtdcCustTypeType<br>
	 * @param AccountID 投资者帐号<br>
	 * C type : TThostFtdcAccountIDType<br>
	 * @param Password 期货密码<br>
	 * C type : TThostFtdcPasswordType<br>
	 * @param CurrencyID 币种代码<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	public CThostFtdcVerifyFuturePasswordAndCustInfoField(byte CustomerName[], byte IdCardType, byte IdentifiedCardNo[], byte CustType, byte AccountID[], byte Password[], byte CurrencyID[]) {
		super();
		if ((CustomerName.length != this.CustomerName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.CustomerName = CustomerName;
		this.IdCardType = IdCardType;
		if ((IdentifiedCardNo.length != this.IdentifiedCardNo.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.IdentifiedCardNo = IdentifiedCardNo;
		this.CustType = CustType;
		if ((AccountID.length != this.AccountID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.AccountID = AccountID;
		if ((Password.length != this.Password.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.Password = Password;
		if ((CurrencyID.length != this.CurrencyID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.CurrencyID = CurrencyID;
	}
	public static class ByReference extends CThostFtdcVerifyFuturePasswordAndCustInfoField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcVerifyFuturePasswordAndCustInfoField implements Structure.ByValue {
		
	};
}
