package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 投资者结算结果确认信息<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:1796</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcSettlementInfoConfirmField extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	public byte[] InvestorID = new byte[13];
	/**
	 * 确认日期<br>
	 * C type : TThostFtdcDateType
	 */
	public byte[] ConfirmDate = new byte[9];
	/**
	 * 确认时间<br>
	 * C type : TThostFtdcTimeType
	 */
	public byte[] ConfirmTime = new byte[9];
	public CThostFtdcSettlementInfoConfirmField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "InvestorID", "ConfirmDate", "ConfirmTime");
	}
	/**
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param InvestorID 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType<br>
	 * @param ConfirmDate 确认日期<br>
	 * C type : TThostFtdcDateType<br>
	 * @param ConfirmTime 确认时间<br>
	 * C type : TThostFtdcTimeType
	 */
	public CThostFtdcSettlementInfoConfirmField(byte BrokerID[], byte InvestorID[], byte ConfirmDate[], byte ConfirmTime[]) {
		super();
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		if ((InvestorID.length != this.InvestorID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.InvestorID = InvestorID;
		if ((ConfirmDate.length != this.ConfirmDate.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ConfirmDate = ConfirmDate;
		if ((ConfirmTime.length != this.ConfirmTime.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ConfirmTime = ConfirmTime;
	}
	public static class ByReference extends CThostFtdcSettlementInfoConfirmField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcSettlementInfoConfirmField implements Structure.ByValue {
		
	};
}
