package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 客户开销户信息表<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:6947</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcAccountregisterField extends Structure {
	/**
	 * 交易日期<br>
	 * C type : TThostFtdcTradeDateType
	 */
	public byte[] TradeDay = new byte[9];
	/**
	 * 银行编码<br>
	 * C type : TThostFtdcBankIDType
	 */
	public byte[] BankID = new byte[4];
	/**
	 * 银行分支机构编码<br>
	 * C type : TThostFtdcBankBrchIDType
	 */
	public byte[] BankBranchID = new byte[5];
	/**
	 * 银行帐号<br>
	 * C type : TThostFtdcBankAccountType
	 */
	public byte[] BankAccount = new byte[41];
	/**
	 * 期货公司编码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 期货公司分支机构编码<br>
	 * C type : TThostFtdcFutureBranchIDType
	 */
	public byte[] BrokerBranchID = new byte[31];
	/**
	 * 投资者帐号<br>
	 * C type : TThostFtdcAccountIDType
	 */
	public byte[] AccountID = new byte[13];
	/**
	 * 证件类型<br>
	 * C type : TThostFtdcIdCardTypeType
	 */
	public byte IdCardType;
	/**
	 * 证件号码<br>
	 * C type : TThostFtdcIdentifiedCardNoType
	 */
	public byte[] IdentifiedCardNo = new byte[51];
	/**
	 * 客户姓名<br>
	 * C type : TThostFtdcIndividualNameType
	 */
	public byte[] CustomerName = new byte[51];
	/**
	 * 币种代码<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	public byte[] CurrencyID = new byte[4];
	/**
	 * 开销户类别<br>
	 * C type : TThostFtdcOpenOrDestroyType
	 */
	public byte OpenOrDestroy;
	/**
	 * 签约日期<br>
	 * C type : TThostFtdcTradeDateType
	 */
	public byte[] RegDate = new byte[9];
	/**
	 * 解约日期<br>
	 * C type : TThostFtdcTradeDateType
	 */
	public byte[] OutDate = new byte[9];
	/**
	 * 交易ID<br>
	 * C type : TThostFtdcTIDType
	 */
	public int TID;
	/**
	 * 客户类型<br>
	 * C type : TThostFtdcCustTypeType
	 */
	public byte CustType;
	/**
	 * 银行帐号类型<br>
	 * C type : TThostFtdcBankAccTypeType
	 */
	public byte BankAccType;
	public CThostFtdcAccountregisterField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("TradeDay", "BankID", "BankBranchID", "BankAccount", "BrokerID", "BrokerBranchID", "AccountID", "IdCardType", "IdentifiedCardNo", "CustomerName", "CurrencyID", "OpenOrDestroy", "RegDate", "OutDate", "TID", "CustType", "BankAccType");
	}
	public static class ByReference extends CThostFtdcAccountregisterField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcAccountregisterField implements Structure.ByValue {
		
	};
}
