package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 成交均价<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:4541</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcMarketDataAveragePriceField extends Structure {
	/**
	 * 当日均价<br>
	 * C type : TThostFtdcPriceType
	 */
	public double AveragePrice;
	public CThostFtdcMarketDataAveragePriceField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("AveragePrice");
	}
	/**
	 * @param AveragePrice 当日均价<br>
	 * C type : TThostFtdcPriceType
	 */
	public CThostFtdcMarketDataAveragePriceField(double AveragePrice) {
		super();
		this.AveragePrice = AveragePrice;
	}
	public static class ByReference extends CThostFtdcMarketDataAveragePriceField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcMarketDataAveragePriceField implements Structure.ByValue {
		
	};
}
