package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 查询银行交易明细请求响应<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:269</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcTransferQryDetailRspField extends Structure {
	/**
	 * 交易日期<br>
	 * C type : TThostFtdcDateType
	 */
	public byte[] TradeDate = new byte[9];
	/**
	 * 交易时间<br>
	 * C type : TThostFtdcTradeTimeType
	 */
	public byte[] TradeTime = new byte[9];
	/**
	 * 交易代码<br>
	 * C type : TThostFtdcTradeCodeType
	 */
	public byte[] TradeCode = new byte[7];
	/**
	 * 期货流水号<br>
	 * C type : TThostFtdcTradeSerialNoType
	 */
	public int FutureSerial;
	/**
	 * 期货公司代码<br>
	 * C type : TThostFtdcFutureIDType
	 */
	public byte[] FutureID = new byte[11];
	/**
	 * 资金帐号<br>
	 * C type : TThostFtdcFutureAccountType
	 */
	public byte[] FutureAccount = new byte[22];
	/**
	 * 银行流水号<br>
	 * C type : TThostFtdcTradeSerialNoType
	 */
	public int BankSerial;
	/**
	 * 银行代码<br>
	 * C type : TThostFtdcBankIDType
	 */
	public byte[] BankID = new byte[4];
	/**
	 * 银行分中心代码<br>
	 * C type : TThostFtdcBankBrchIDType
	 */
	public byte[] BankBrchID = new byte[5];
	/**
	 * 银行账号<br>
	 * C type : TThostFtdcBankAccountType
	 */
	public byte[] BankAccount = new byte[41];
	/**
	 * 证件号码<br>
	 * C type : TThostFtdcCertCodeType
	 */
	public byte[] CertCode = new byte[21];
	/**
	 * 货币代码<br>
	 * C type : TThostFtdcCurrencyCodeType
	 */
	public byte[] CurrencyCode = new byte[4];
	/**
	 * 发生金额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double TxAmount;
	/**
	 * 有效标志<br>
	 * C type : TThostFtdcTransferValidFlagType
	 */
	public byte Flag;
	public CThostFtdcTransferQryDetailRspField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("TradeDate", "TradeTime", "TradeCode", "FutureSerial", "FutureID", "FutureAccount", "BankSerial", "BankID", "BankBrchID", "BankAccount", "CertCode", "CurrencyCode", "TxAmount", "Flag");
	}
	public static class ByReference extends CThostFtdcTransferQryDetailRspField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcTransferQryDetailRspField implements Structure.ByValue {
		
	};
}
