package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 用户登录请求<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:18</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcReqUserLoginField extends Structure {
	/**
	 * 交易日<br>
	 * C type : TThostFtdcDateType
	 */
	public byte[] TradingDay = new byte[9];
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 用户代码<br>
	 * C type : TThostFtdcUserIDType
	 */
	public byte[] UserID = new byte[16];
	/**
	 * 密码<br>
	 * C type : TThostFtdcPasswordType
	 */
	public byte[] Password = new byte[41];
	/**
	 * 用户端产品信息<br>
	 * C type : TThostFtdcProductInfoType
	 */
	public byte[] UserProductInfo = new byte[11];
	/**
	 * 接口端产品信息<br>
	 * C type : TThostFtdcProductInfoType
	 */
	public byte[] InterfaceProductInfo = new byte[11];
	/**
	 * 协议信息<br>
	 * C type : TThostFtdcProtocolInfoType
	 */
	public byte[] ProtocolInfo = new byte[11];
	/**
	 * Mac地址<br>
	 * C type : TThostFtdcMacAddressType
	 */
	public byte[] MacAddress = new byte[21];
	/**
	 * 动态密码<br>
	 * C type : TThostFtdcPasswordType
	 */
	public byte[] OneTimePassword = new byte[41];
	/**
	 * 终端IP地址<br>
	 * C type : TThostFtdcIPAddressType
	 */
	public byte[] ClientIPAddress = new byte[16];
	public CThostFtdcReqUserLoginField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("TradingDay", "BrokerID", "UserID", "Password", "UserProductInfo", "InterfaceProductInfo", "ProtocolInfo", "MacAddress", "OneTimePassword", "ClientIPAddress");
	}
	public static class ByReference extends CThostFtdcReqUserLoginField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcReqUserLoginField implements Structure.ByValue {
		
	};
}
