package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 查询管理用户功能权限<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:2312</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcQrySuperUserFunctionField extends Structure {
	/**
	 * 用户代码<br>
	 * C type : TThostFtdcUserIDType
	 */
	public byte[] UserID = new byte[16];
	public CThostFtdcQrySuperUserFunctionField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("UserID");
	}
	/**
	 * @param UserID 用户代码<br>
	 * C type : TThostFtdcUserIDType
	 */
	public CThostFtdcQrySuperUserFunctionField(byte UserID[]) {
		super();
		if ((UserID.length != this.UserID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.UserID = UserID;
	}
	public static class ByReference extends CThostFtdcQrySuperUserFunctionField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcQrySuperUserFunctionField implements Structure.ByValue {
		
	};
}
