package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 通讯阶段<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:1119</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcCommPhaseField extends Structure {
	/**
	 * 交易日<br>
	 * C type : TThostFtdcDateType
	 */
	public byte[] TradingDay = new byte[9];
	/**
	 * 通讯时段编号<br>
	 * C type : TThostFtdcCommPhaseNoType
	 */
	public short CommPhaseNo;
	/**
	 * 系统编号<br>
	 * C type : TThostFtdcSystemIDType
	 */
	public byte[] SystemID = new byte[21];
	public CThostFtdcCommPhaseField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("TradingDay", "CommPhaseNo", "SystemID");
	}
	/**
	 * @param TradingDay 交易日<br>
	 * C type : TThostFtdcDateType<br>
	 * @param CommPhaseNo 通讯时段编号<br>
	 * C type : TThostFtdcCommPhaseNoType<br>
	 * @param SystemID 系统编号<br>
	 * C type : TThostFtdcSystemIDType
	 */
	public CThostFtdcCommPhaseField(byte TradingDay[], short CommPhaseNo, byte SystemID[]) {
		super();
		if ((TradingDay.length != this.TradingDay.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.TradingDay = TradingDay;
		this.CommPhaseNo = CommPhaseNo;
		if ((SystemID.length != this.SystemID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.SystemID = SystemID;
	}
	public static class ByReference extends CThostFtdcCommPhaseField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcCommPhaseField implements Structure.ByValue {
		
	};
}
