package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 请求查询投资者手续费率模板<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:5110</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcQryCommRateModelField extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 手续费率模板代码<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	public byte[] CommModelID = new byte[13];
	public CThostFtdcQryCommRateModelField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "CommModelID");
	}
	/**
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param CommModelID 手续费率模板代码<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	public CThostFtdcQryCommRateModelField(byte BrokerID[], byte CommModelID[]) {
		super();
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		if ((CommModelID.length != this.CommModelID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.CommModelID = CommModelID;
	}
	public static class ByReference extends CThostFtdcQryCommRateModelField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcQryCommRateModelField implements Structure.ByValue {
		
	};
}
