package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 期权交易成本<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:2621</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcOptionInstrTradeCostField extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	public byte[] InvestorID = new byte[13];
	/**
	 * 合约代码<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	public byte[] InstrumentID = new byte[31];
	/**
	 * 投机套保标志<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	public byte HedgeFlag;
	/**
	 * 期权合约保证金不变部分<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double FixedMargin;
	/**
	 * 期权合约最小保证金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double MiniMargin;
	/**
	 * 期权合约权利金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double Royalty;
	/**
	 * 交易所期权合约保证金不变部分<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double ExchFixedMargin;
	/**
	 * 交易所期权合约最小保证金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double ExchMiniMargin;
	public CThostFtdcOptionInstrTradeCostField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "InvestorID", "InstrumentID", "HedgeFlag", "FixedMargin", "MiniMargin", "Royalty", "ExchFixedMargin", "ExchMiniMargin");
	}
	/**
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param InvestorID 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType<br>
	 * @param InstrumentID 合约代码<br>
	 * C type : TThostFtdcInstrumentIDType<br>
	 * @param HedgeFlag 投机套保标志<br>
	 * C type : TThostFtdcHedgeFlagType<br>
	 * @param FixedMargin 期权合约保证金不变部分<br>
	 * C type : TThostFtdcMoneyType<br>
	 * @param MiniMargin 期权合约最小保证金<br>
	 * C type : TThostFtdcMoneyType<br>
	 * @param Royalty 期权合约权利金<br>
	 * C type : TThostFtdcMoneyType<br>
	 * @param ExchFixedMargin 交易所期权合约保证金不变部分<br>
	 * C type : TThostFtdcMoneyType<br>
	 * @param ExchMiniMargin 交易所期权合约最小保证金<br>
	 * C type : TThostFtdcMoneyType
	 */
	public CThostFtdcOptionInstrTradeCostField(byte BrokerID[], byte InvestorID[], byte InstrumentID[], byte HedgeFlag, double FixedMargin, double MiniMargin, double Royalty, double ExchFixedMargin, double ExchMiniMargin) {
		super();
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		if ((InvestorID.length != this.InvestorID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.InvestorID = InvestorID;
		if ((InstrumentID.length != this.InstrumentID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.InstrumentID = InstrumentID;
		this.HedgeFlag = HedgeFlag;
		this.FixedMargin = FixedMargin;
		this.MiniMargin = MiniMargin;
		this.Royalty = Royalty;
		this.ExchFixedMargin = ExchFixedMargin;
		this.ExchMiniMargin = ExchMiniMargin;
	}
	public static class ByReference extends CThostFtdcOptionInstrTradeCostField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcOptionInstrTradeCostField implements Structure.ByValue {
		
	};
}
