package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 灾备中心交易权限<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:7297</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcUserRightsAssignField extends Structure {
	/**
	 * 应用单元代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 用户代码<br>
	 * C type : TThostFtdcUserIDType
	 */
	public byte[] UserID = new byte[16];
	/**
	 * 交易中心代码<br>
	 * C type : TThostFtdcDRIdentityIDType
	 */
	public int DRIdentityID;
	public CThostFtdcUserRightsAssignField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "UserID", "DRIdentityID");
	}
	/**
	 * @param BrokerID 应用单元代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param UserID 用户代码<br>
	 * C type : TThostFtdcUserIDType<br>
	 * @param DRIdentityID 交易中心代码<br>
	 * C type : TThostFtdcDRIdentityIDType
	 */
	public CThostFtdcUserRightsAssignField(byte BrokerID[], byte UserID[], int DRIdentityID) {
		super();
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		if ((UserID.length != this.UserID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.UserID = UserID;
		this.DRIdentityID = DRIdentityID;
	}
	public static class ByReference extends CThostFtdcUserRightsAssignField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcUserRightsAssignField implements Structure.ByValue {
		
	};
}
