package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 查询交易所<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:2396</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcQryExchangeField extends Structure {
	/**
	 * 交易所代码<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	public byte[] ExchangeID = new byte[9];
	public CThostFtdcQryExchangeField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("ExchangeID");
	}
	/**
	 * @param ExchangeID 交易所代码<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	public CThostFtdcQryExchangeField(byte ExchangeID[]) {
		super();
		if ((ExchangeID.length != this.ExchangeID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ExchangeID = ExchangeID;
	}
	public static class ByReference extends CThostFtdcQryExchangeField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcQryExchangeField implements Structure.ByValue {
		
	};
}
