package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 转帐银行<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:3926</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcTransferBankField extends Structure {
	/**
	 * 银行代码<br>
	 * C type : TThostFtdcBankIDType
	 */
	public byte[] BankID = new byte[4];
	/**
	 * 银行分中心代码<br>
	 * C type : TThostFtdcBankBrchIDType
	 */
	public byte[] BankBrchID = new byte[5];
	/**
	 * 银行名称<br>
	 * C type : TThostFtdcBankNameType
	 */
	public byte[] BankName = new byte[101];
	/**
	 * 是否活跃<br>
	 * C type : TThostFtdcBoolType
	 */
	public int IsActive;
	public CThostFtdcTransferBankField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BankID", "BankBrchID", "BankName", "IsActive");
	}
	/**
	 * @param BankID 银行代码<br>
	 * C type : TThostFtdcBankIDType<br>
	 * @param BankBrchID 银行分中心代码<br>
	 * C type : TThostFtdcBankBrchIDType<br>
	 * @param BankName 银行名称<br>
	 * C type : TThostFtdcBankNameType<br>
	 * @param IsActive 是否活跃<br>
	 * C type : TThostFtdcBoolType
	 */
	public CThostFtdcTransferBankField(byte BankID[], byte BankBrchID[], byte BankName[], int IsActive) {
		super();
		if ((BankID.length != this.BankID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BankID = BankID;
		if ((BankBrchID.length != this.BankBrchID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BankBrchID = BankBrchID;
		if ((BankName.length != this.BankName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BankName = BankName;
		this.IsActive = IsActive;
	}
	public static class ByReference extends CThostFtdcTransferBankField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcTransferBankField implements Structure.ByValue {
		
	};
}
