package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 发给做市商的询价请求<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:3639</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcForQuoteRspField extends Structure {
	/**
	 * 交易日<br>
	 * C type : TThostFtdcDateType
	 */
	public byte[] TradingDay = new byte[9];
	/**
	 * 合约代码<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	public byte[] InstrumentID = new byte[31];
	/**
	 * 询价编号<br>
	 * C type : TThostFtdcOrderSysIDType
	 */
	public byte[] ForQuoteSysID = new byte[21];
	/**
	 * 询价时间<br>
	 * C type : TThostFtdcTimeType
	 */
	public byte[] ForQuoteTime = new byte[9];
	/**
	 * 业务日期<br>
	 * C type : TThostFtdcDateType
	 */
	public byte[] ActionDay = new byte[9];
	public CThostFtdcForQuoteRspField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("TradingDay", "InstrumentID", "ForQuoteSysID", "ForQuoteTime", "ActionDay");
	}
	/**
	 * @param TradingDay 交易日<br>
	 * C type : TThostFtdcDateType<br>
	 * @param InstrumentID 合约代码<br>
	 * C type : TThostFtdcInstrumentIDType<br>
	 * @param ForQuoteSysID 询价编号<br>
	 * C type : TThostFtdcOrderSysIDType<br>
	 * @param ForQuoteTime 询价时间<br>
	 * C type : TThostFtdcTimeType<br>
	 * @param ActionDay 业务日期<br>
	 * C type : TThostFtdcDateType
	 */
	public CThostFtdcForQuoteRspField(byte TradingDay[], byte InstrumentID[], byte ForQuoteSysID[], byte ForQuoteTime[], byte ActionDay[]) {
		super();
		if ((TradingDay.length != this.TradingDay.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.TradingDay = TradingDay;
		if ((InstrumentID.length != this.InstrumentID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.InstrumentID = InstrumentID;
		if ((ForQuoteSysID.length != this.ForQuoteSysID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ForQuoteSysID = ForQuoteSysID;
		if ((ForQuoteTime.length != this.ForQuoteTime.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ForQuoteTime = ForQuoteTime;
		if ((ActionDay.length != this.ActionDay.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ActionDay = ActionDay;
	}
	public static class ByReference extends CThostFtdcForQuoteRspField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcForQuoteRspField implements Structure.ByValue {
		
	};
}
