package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 期权交易成本查询<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:2644</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcQryOptionInstrTradeCostField extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	public byte[] InvestorID = new byte[13];
	/**
	 * 合约代码<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	public byte[] InstrumentID = new byte[31];
	/**
	 * 投机套保标志<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	public byte HedgeFlag;
	/**
	 * 期权合约报价<br>
	 * C type : TThostFtdcPriceType
	 */
	public double InputPrice;
	/**
	 * 标的价格,填0则用昨结算价<br>
	 * C type : TThostFtdcPriceType
	 */
	public double UnderlyingPrice;
	public CThostFtdcQryOptionInstrTradeCostField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "InvestorID", "InstrumentID", "HedgeFlag", "InputPrice", "UnderlyingPrice");
	}
	/**
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param InvestorID 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType<br>
	 * @param InstrumentID 合约代码<br>
	 * C type : TThostFtdcInstrumentIDType<br>
	 * @param HedgeFlag 投机套保标志<br>
	 * C type : TThostFtdcHedgeFlagType<br>
	 * @param InputPrice 期权合约报价<br>
	 * C type : TThostFtdcPriceType<br>
	 * @param UnderlyingPrice 标的价格,填0则用昨结算价<br>
	 * C type : TThostFtdcPriceType
	 */
	public CThostFtdcQryOptionInstrTradeCostField(byte BrokerID[], byte InvestorID[], byte InstrumentID[], byte HedgeFlag, double InputPrice, double UnderlyingPrice) {
		super();
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		if ((InvestorID.length != this.InvestorID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.InvestorID = InvestorID;
		if ((InstrumentID.length != this.InstrumentID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.InstrumentID = InstrumentID;
		this.HedgeFlag = HedgeFlag;
		this.InputPrice = InputPrice;
		this.UnderlyingPrice = UnderlyingPrice;
	}
	public static class ByReference extends CThostFtdcQryOptionInstrTradeCostField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcQryOptionInstrTradeCostField implements Structure.ByValue {
		
	};
}
