package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 用户口令变更<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:1199</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcUserPasswordUpdateField extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 用户代码<br>
	 * C type : TThostFtdcUserIDType
	 */
	public byte[] UserID = new byte[16];
	/**
	 * 原来的口令<br>
	 * C type : TThostFtdcPasswordType
	 */
	public byte[] OldPassword = new byte[41];
	/**
	 * 新的口令<br>
	 * C type : TThostFtdcPasswordType
	 */
	public byte[] NewPassword = new byte[41];
	public CThostFtdcUserPasswordUpdateField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "UserID", "OldPassword", "NewPassword");
	}
	/**
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param UserID 用户代码<br>
	 * C type : TThostFtdcUserIDType<br>
	 * @param OldPassword 原来的口令<br>
	 * C type : TThostFtdcPasswordType<br>
	 * @param NewPassword 新的口令<br>
	 * C type : TThostFtdcPasswordType
	 */
	public CThostFtdcUserPasswordUpdateField(byte BrokerID[], byte UserID[], byte OldPassword[], byte NewPassword[]) {
		super();
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		if ((UserID.length != this.UserID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.UserID = UserID;
		if ((OldPassword.length != this.OldPassword.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.OldPassword = OldPassword;
		if ((NewPassword.length != this.NewPassword.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.NewPassword = NewPassword;
	}
	public static class ByReference extends CThostFtdcUserPasswordUpdateField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcUserPasswordUpdateField implements Structure.ByValue {
		
	};
}
