package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 会员编码和经纪公司编码对照表<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:506</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcPartBrokerField extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 交易所代码<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	public byte[] ExchangeID = new byte[9];
	/**
	 * 会员代码<br>
	 * C type : TThostFtdcParticipantIDType
	 */
	public byte[] ParticipantID = new byte[11];
	/**
	 * 是否活跃<br>
	 * C type : TThostFtdcBoolType
	 */
	public int IsActive;
	public CThostFtdcPartBrokerField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "ExchangeID", "ParticipantID", "IsActive");
	}
	/**
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param ExchangeID 交易所代码<br>
	 * C type : TThostFtdcExchangeIDType<br>
	 * @param ParticipantID 会员代码<br>
	 * C type : TThostFtdcParticipantIDType<br>
	 * @param IsActive 是否活跃<br>
	 * C type : TThostFtdcBoolType
	 */
	public CThostFtdcPartBrokerField(byte BrokerID[], byte ExchangeID[], byte ParticipantID[], int IsActive) {
		super();
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		if ((ExchangeID.length != this.ExchangeID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ExchangeID = ExchangeID;
		if ((ParticipantID.length != this.ParticipantID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ParticipantID = ParticipantID;
		this.IsActive = IsActive;
	}
	public static class ByReference extends CThostFtdcPartBrokerField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcPartBrokerField implements Structure.ByValue {
		
	};
}
