package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 查询合约状态<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:3867</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcQryInstrumentStatusField extends Structure {
	/**
	 * 交易所代码<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	public byte[] ExchangeID = new byte[9];
	/**
	 * 合约在交易所的代码<br>
	 * C type : TThostFtdcExchangeInstIDType
	 */
	public byte[] ExchangeInstID = new byte[31];
	public CThostFtdcQryInstrumentStatusField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("ExchangeID", "ExchangeInstID");
	}
	/**
	 * @param ExchangeID 交易所代码<br>
	 * C type : TThostFtdcExchangeIDType<br>
	 * @param ExchangeInstID 合约在交易所的代码<br>
	 * C type : TThostFtdcExchangeInstIDType
	 */
	public CThostFtdcQryInstrumentStatusField(byte ExchangeID[], byte ExchangeInstID[]) {
		super();
		if ((ExchangeID.length != this.ExchangeID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ExchangeID = ExchangeID;
		if ((ExchangeInstID.length != this.ExchangeInstID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ExchangeInstID = ExchangeInstID;
	}
	public static class ByReference extends CThostFtdcQryInstrumentStatusField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcQryInstrumentStatusField implements Structure.ByValue {
		
	};
}
