package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 查询组合持仓明细<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:4530</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcQryInvestorPositionCombineDetailField extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	public byte[] InvestorID = new byte[13];
	/**
	 * 组合持仓合约编码<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	public byte[] CombInstrumentID = new byte[31];
	public CThostFtdcQryInvestorPositionCombineDetailField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "InvestorID", "CombInstrumentID");
	}
	/**
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param InvestorID 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType<br>
	 * @param CombInstrumentID 组合持仓合约编码<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	public CThostFtdcQryInvestorPositionCombineDetailField(byte BrokerID[], byte InvestorID[], byte CombInstrumentID[]) {
		super();
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		if ((InvestorID.length != this.InvestorID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.InvestorID = InvestorID;
		if ((CombInstrumentID.length != this.CombInstrumentID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.CombInstrumentID = CombInstrumentID;
	}
	public static class ByReference extends CThostFtdcQryInvestorPositionCombineDetailField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcQryInvestorPositionCombineDetailField implements Structure.ByValue {
		
	};
}
