package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 查询出入金流水<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:2461</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcQrySyncDepositField extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 出入金流水号<br>
	 * C type : TThostFtdcDepositSeqNoType
	 */
	public byte[] DepositSeqNo = new byte[15];
	public CThostFtdcQrySyncDepositField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "DepositSeqNo");
	}
	/**
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param DepositSeqNo 出入金流水号<br>
	 * C type : TThostFtdcDepositSeqNoType
	 */
	public CThostFtdcQrySyncDepositField(byte BrokerID[], byte DepositSeqNo[]) {
		super();
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		if ((DepositSeqNo.length != this.DepositSeqNo.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.DepositSeqNo = DepositSeqNo;
	}
	public static class ByReference extends CThostFtdcQrySyncDepositField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcQrySyncDepositField implements Structure.ByValue {
		
	};
}
