package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 保证金监管系统经纪公司密钥<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:5020</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcCFMMCBrokerKeyField extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 经纪公司统一编码<br>
	 * C type : TThostFtdcParticipantIDType
	 */
	public byte[] ParticipantID = new byte[11];
	/**
	 * 密钥生成日期<br>
	 * C type : TThostFtdcDateType
	 */
	public byte[] CreateDate = new byte[9];
	/**
	 * 密钥生成时间<br>
	 * C type : TThostFtdcTimeType
	 */
	public byte[] CreateTime = new byte[9];
	/**
	 * 密钥编号<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	public int KeyID;
	/**
	 * 动态密钥<br>
	 * C type : TThostFtdcCFMMCKeyType
	 */
	public byte[] CurrentKey = new byte[21];
	/**
	 * 动态密钥类型<br>
	 * C type : TThostFtdcCFMMCKeyKindType
	 */
	public byte KeyKind;
	public CThostFtdcCFMMCBrokerKeyField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "ParticipantID", "CreateDate", "CreateTime", "KeyID", "CurrentKey", "KeyKind");
	}
	/**
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param ParticipantID 经纪公司统一编码<br>
	 * C type : TThostFtdcParticipantIDType<br>
	 * @param CreateDate 密钥生成日期<br>
	 * C type : TThostFtdcDateType<br>
	 * @param CreateTime 密钥生成时间<br>
	 * C type : TThostFtdcTimeType<br>
	 * @param KeyID 密钥编号<br>
	 * C type : TThostFtdcSequenceNoType<br>
	 * @param CurrentKey 动态密钥<br>
	 * C type : TThostFtdcCFMMCKeyType<br>
	 * @param KeyKind 动态密钥类型<br>
	 * C type : TThostFtdcCFMMCKeyKindType
	 */
	public CThostFtdcCFMMCBrokerKeyField(byte BrokerID[], byte ParticipantID[], byte CreateDate[], byte CreateTime[], int KeyID, byte CurrentKey[], byte KeyKind) {
		super();
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		if ((ParticipantID.length != this.ParticipantID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ParticipantID = ParticipantID;
		if ((CreateDate.length != this.CreateDate.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.CreateDate = CreateDate;
		if ((CreateTime.length != this.CreateTime.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.CreateTime = CreateTime;
		this.KeyID = KeyID;
		if ((CurrentKey.length != this.CurrentKey.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.CurrentKey = CurrentKey;
		this.KeyKind = KeyKind;
	}
	public static class ByReference extends CThostFtdcCFMMCBrokerKeyField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcCFMMCBrokerKeyField implements Structure.ByValue {
		
	};
}
