package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 客户端认证请求<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:92</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcReqAuthenticateField extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 用户代码<br>
	 * C type : TThostFtdcUserIDType
	 */
	public byte[] UserID = new byte[16];
	/**
	 * 用户端产品信息<br>
	 * C type : TThostFtdcProductInfoType
	 */
	public byte[] UserProductInfo = new byte[11];
	/**
	 * 认证码<br>
	 * C type : TThostFtdcAuthCodeType
	 */
	public byte[] AuthCode = new byte[17];
	public CThostFtdcReqAuthenticateField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "UserID", "UserProductInfo", "AuthCode");
	}
	/**
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param UserID 用户代码<br>
	 * C type : TThostFtdcUserIDType<br>
	 * @param UserProductInfo 用户端产品信息<br>
	 * C type : TThostFtdcProductInfoType<br>
	 * @param AuthCode 认证码<br>
	 * C type : TThostFtdcAuthCodeType
	 */
	public CThostFtdcReqAuthenticateField(byte BrokerID[], byte UserID[], byte UserProductInfo[], byte AuthCode[]) {
		super();
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		if ((UserID.length != this.UserID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.UserID = UserID;
		if ((UserProductInfo.length != this.UserProductInfo.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.UserProductInfo = UserProductInfo;
		if ((AuthCode.length != this.AuthCode.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.AuthCode = AuthCode;
	}
	public static class ByReference extends CThostFtdcReqAuthenticateField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcReqAuthenticateField implements Structure.ByValue {
		
	};
}
