package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 银期转账交易流水表<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:6703</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcTransferSerialField extends Structure {
	/**
	 * 平台流水号<br>
	 * C type : TThostFtdcPlateSerialType
	 */
	public int PlateSerial;
	/**
	 * 交易发起方日期<br>
	 * C type : TThostFtdcTradeDateType
	 */
	public byte[] TradeDate = new byte[9];
	/**
	 * 交易日期<br>
	 * C type : TThostFtdcDateType
	 */
	public byte[] TradingDay = new byte[9];
	/**
	 * 交易时间<br>
	 * C type : TThostFtdcTradeTimeType
	 */
	public byte[] TradeTime = new byte[9];
	/**
	 * 交易代码<br>
	 * C type : TThostFtdcTradeCodeType
	 */
	public byte[] TradeCode = new byte[7];
	/**
	 * 会话编号<br>
	 * C type : TThostFtdcSessionIDType
	 */
	public int SessionID;
	/**
	 * 银行编码<br>
	 * C type : TThostFtdcBankIDType
	 */
	public byte[] BankID = new byte[4];
	/**
	 * 银行分支机构编码<br>
	 * C type : TThostFtdcBankBrchIDType
	 */
	public byte[] BankBranchID = new byte[5];
	/**
	 * 银行帐号类型<br>
	 * C type : TThostFtdcBankAccTypeType
	 */
	public byte BankAccType;
	/**
	 * 银行帐号<br>
	 * C type : TThostFtdcBankAccountType
	 */
	public byte[] BankAccount = new byte[41];
	/**
	 * 银行流水号<br>
	 * C type : TThostFtdcBankSerialType
	 */
	public byte[] BankSerial = new byte[13];
	/**
	 * 期货公司编码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 期商分支机构代码<br>
	 * C type : TThostFtdcFutureBranchIDType
	 */
	public byte[] BrokerBranchID = new byte[31];
	/**
	 * 期货公司帐号类型<br>
	 * C type : TThostFtdcFutureAccTypeType
	 */
	public byte FutureAccType;
	/**
	 * 投资者帐号<br>
	 * C type : TThostFtdcAccountIDType
	 */
	public byte[] AccountID = new byte[13];
	/**
	 * 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	public byte[] InvestorID = new byte[13];
	/**
	 * 期货公司流水号<br>
	 * C type : TThostFtdcFutureSerialType
	 */
	public int FutureSerial;
	/**
	 * 证件类型<br>
	 * C type : TThostFtdcIdCardTypeType
	 */
	public byte IdCardType;
	/**
	 * 证件号码<br>
	 * C type : TThostFtdcIdentifiedCardNoType
	 */
	public byte[] IdentifiedCardNo = new byte[51];
	/**
	 * 币种代码<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	public byte[] CurrencyID = new byte[4];
	/**
	 * 交易金额<br>
	 * C type : TThostFtdcTradeAmountType
	 */
	public double TradeAmount;
	/**
	 * 应收客户费用<br>
	 * C type : TThostFtdcCustFeeType
	 */
	public double CustFee;
	/**
	 * 应收期货公司费用<br>
	 * C type : TThostFtdcFutureFeeType
	 */
	public double BrokerFee;
	/**
	 * 有效标志<br>
	 * C type : TThostFtdcAvailabilityFlagType
	 */
	public byte AvailabilityFlag;
	/**
	 * 操作员<br>
	 * C type : TThostFtdcOperatorCodeType
	 */
	public byte[] OperatorCode = new byte[17];
	/**
	 * 新银行帐号<br>
	 * C type : TThostFtdcBankAccountType
	 */
	public byte[] BankNewAccount = new byte[41];
	/**
	 * 错误代码<br>
	 * C type : TThostFtdcErrorIDType
	 */
	public int ErrorID;
	/**
	 * 错误信息<br>
	 * C type : TThostFtdcErrorMsgType
	 */
	public byte[] ErrorMsg = new byte[81];
	public CThostFtdcTransferSerialField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("PlateSerial", "TradeDate", "TradingDay", "TradeTime", "TradeCode", "SessionID", "BankID", "BankBranchID", "BankAccType", "BankAccount", "BankSerial", "BrokerID", "BrokerBranchID", "FutureAccType", "AccountID", "InvestorID", "FutureSerial", "IdCardType", "IdentifiedCardNo", "CurrencyID", "TradeAmount", "CustFee", "BrokerFee", "AvailabilityFlag", "OperatorCode", "BankNewAccount", "ErrorID", "ErrorMsg");
	}
	public static class ByReference extends CThostFtdcTransferSerialField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcTransferSerialField implements Structure.ByValue {
		
	};
}
