package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 经纪公司可提资金算法表<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:4121</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcBrokerWithdrawAlgorithmField extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 可提资金算法<br>
	 * C type : TThostFtdcAlgorithmType
	 */
	public byte WithdrawAlgorithm;
	/**
	 * 资金使用率<br>
	 * C type : TThostFtdcRatioType
	 */
	public double UsingRatio;
	/**
	 * 可提是否包含平仓盈利<br>
	 * C type : TThostFtdcIncludeCloseProfitType
	 */
	public byte IncludeCloseProfit;
	/**
	 * 本日无仓且无成交客户是否受可提比例限制<br>
	 * C type : TThostFtdcAllWithoutTradeType
	 */
	public byte AllWithoutTrade;
	/**
	 * 可用是否包含平仓盈利<br>
	 * C type : TThostFtdcIncludeCloseProfitType
	 */
	public byte AvailIncludeCloseProfit;
	/**
	 * 是否启用用户事件<br>
	 * C type : TThostFtdcBoolType
	 */
	public int IsBrokerUserEvent;
	/**
	 * 币种代码<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	public byte[] CurrencyID = new byte[4];
	/**
	 * 货币质押比率<br>
	 * C type : TThostFtdcRatioType
	 */
	public double FundMortgageRatio;
	/**
	 * 权益算法<br>
	 * C type : TThostFtdcBalanceAlgorithmType
	 */
	public byte BalanceAlgorithm;
	public CThostFtdcBrokerWithdrawAlgorithmField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "WithdrawAlgorithm", "UsingRatio", "IncludeCloseProfit", "AllWithoutTrade", "AvailIncludeCloseProfit", "IsBrokerUserEvent", "CurrencyID", "FundMortgageRatio", "BalanceAlgorithm");
	}
	public static class ByReference extends CThostFtdcBrokerWithdrawAlgorithmField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcBrokerWithdrawAlgorithmField implements Structure.ByValue {
		
	};
}
