package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 当前期权合约手续费的详细内容<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:2592</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcOptionInstrCommRateField extends Structure {
	/**
	 * 合约代码<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	public byte[] InstrumentID = new byte[31];
	/**
	 * 投资者范围<br>
	 * C type : TThostFtdcInvestorRangeType
	 */
	public byte InvestorRange;
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	public byte[] InvestorID = new byte[13];
	/**
	 * 开仓手续费率<br>
	 * C type : TThostFtdcRatioType
	 */
	public double OpenRatioByMoney;
	/**
	 * 开仓手续费<br>
	 * C type : TThostFtdcRatioType
	 */
	public double OpenRatioByVolume;
	/**
	 * 平仓手续费率<br>
	 * C type : TThostFtdcRatioType
	 */
	public double CloseRatioByMoney;
	/**
	 * 平仓手续费<br>
	 * C type : TThostFtdcRatioType
	 */
	public double CloseRatioByVolume;
	/**
	 * 平今手续费率<br>
	 * C type : TThostFtdcRatioType
	 */
	public double CloseTodayRatioByMoney;
	/**
	 * 平今手续费<br>
	 * C type : TThostFtdcRatioType
	 */
	public double CloseTodayRatioByVolume;
	/**
	 * 执行手续费率<br>
	 * C type : TThostFtdcRatioType
	 */
	public double StrikeRatioByMoney;
	/**
	 * 执行手续费<br>
	 * C type : TThostFtdcRatioType
	 */
	public double StrikeRatioByVolume;
	public CThostFtdcOptionInstrCommRateField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("InstrumentID", "InvestorRange", "BrokerID", "InvestorID", "OpenRatioByMoney", "OpenRatioByVolume", "CloseRatioByMoney", "CloseRatioByVolume", "CloseTodayRatioByMoney", "CloseTodayRatioByVolume", "StrikeRatioByMoney", "StrikeRatioByVolume");
	}
	public static class ByReference extends CThostFtdcOptionInstrCommRateField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcOptionInstrCommRateField implements Structure.ByValue {
		
	};
}
