package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 会员资金折扣<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:3904</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcDiscountField extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 投资者范围<br>
	 * C type : TThostFtdcInvestorRangeType
	 */
	public byte InvestorRange;
	/**
	 * 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	public byte[] InvestorID = new byte[13];
	/**
	 * 资金折扣比例<br>
	 * C type : TThostFtdcRatioType
	 */
	public double Discount;
	public CThostFtdcDiscountField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "InvestorRange", "InvestorID", "Discount");
	}
	/**
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param InvestorRange 投资者范围<br>
	 * C type : TThostFtdcInvestorRangeType<br>
	 * @param InvestorID 投资者代码<br>
	 * C type : TThostFtdcInvestorIDType<br>
	 * @param Discount 资金折扣比例<br>
	 * C type : TThostFtdcRatioType
	 */
	public CThostFtdcDiscountField(byte BrokerID[], byte InvestorRange, byte InvestorID[], double Discount) {
		super();
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		this.InvestorRange = InvestorRange;
		if ((InvestorID.length != this.InvestorID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.InvestorID = InvestorID;
		this.Discount = Discount;
	}
	public static class ByReference extends CThostFtdcDiscountField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcDiscountField implements Structure.ByValue {
		
	};
}
