package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 查询银行交易明细请求，TradeCode=204999<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:262</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcTransferQryDetailReqField extends Structure {
	/**
	 * 期货资金账户<br>
	 * C type : TThostFtdcAccountIDType
	 */
	public byte[] FutureAccount = new byte[13];
	public CThostFtdcTransferQryDetailReqField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("FutureAccount");
	}
	/**
	 * @param FutureAccount 期货资金账户<br>
	 * C type : TThostFtdcAccountIDType
	 */
	public CThostFtdcTransferQryDetailReqField(byte FutureAccount[]) {
		super();
		if ((FutureAccount.length != this.FutureAccount.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.FutureAccount = FutureAccount;
	}
	public static class ByReference extends CThostFtdcTransferQryDetailReqField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcTransferQryDetailReqField implements Structure.ByValue {
		
	};
}
