package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 组合交易合约的单腿<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:4192</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcCombinationLegField extends Structure {
	/**
	 * 组合合约代码<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	public byte[] CombInstrumentID = new byte[31];
	/**
	 * 单腿编号<br>
	 * C type : TThostFtdcLegIDType
	 */
	public int LegID;
	/**
	 * 单腿合约代码<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	public byte[] LegInstrumentID = new byte[31];
	/**
	 * 买卖方向<br>
	 * C type : TThostFtdcDirectionType
	 */
	public byte Direction;
	/**
	 * 单腿乘数<br>
	 * C type : TThostFtdcLegMultipleType
	 */
	public int LegMultiple;
	/**
	 * 派生层数<br>
	 * C type : TThostFtdcImplyLevelType
	 */
	public int ImplyLevel;
	public CThostFtdcCombinationLegField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("CombInstrumentID", "LegID", "LegInstrumentID", "Direction", "LegMultiple", "ImplyLevel");
	}
	/**
	 * @param CombInstrumentID 组合合约代码<br>
	 * C type : TThostFtdcInstrumentIDType<br>
	 * @param LegID 单腿编号<br>
	 * C type : TThostFtdcLegIDType<br>
	 * @param LegInstrumentID 单腿合约代码<br>
	 * C type : TThostFtdcInstrumentIDType<br>
	 * @param Direction 买卖方向<br>
	 * C type : TThostFtdcDirectionType<br>
	 * @param LegMultiple 单腿乘数<br>
	 * C type : TThostFtdcLegMultipleType<br>
	 * @param ImplyLevel 派生层数<br>
	 * C type : TThostFtdcImplyLevelType
	 */
	public CThostFtdcCombinationLegField(byte CombInstrumentID[], int LegID, byte LegInstrumentID[], byte Direction, int LegMultiple, int ImplyLevel) {
		super();
		if ((CombInstrumentID.length != this.CombInstrumentID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.CombInstrumentID = CombInstrumentID;
		this.LegID = LegID;
		if ((LegInstrumentID.length != this.LegInstrumentID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.LegInstrumentID = LegInstrumentID;
		this.Direction = Direction;
		this.LegMultiple = LegMultiple;
		this.ImplyLevel = ImplyLevel;
	}
	public static class ByReference extends CThostFtdcCombinationLegField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcCombinationLegField implements Structure.ByValue {
		
	};
}
