package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 行情最新成交属性<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:3741</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcMarketDataLastMatchField extends Structure {
	/**
	 * 最新价<br>
	 * C type : TThostFtdcPriceType
	 */
	public double LastPrice;
	/**
	 * 数量<br>
	 * C type : TThostFtdcVolumeType
	 */
	public int Volume;
	/**
	 * 成交金额<br>
	 * C type : TThostFtdcMoneyType
	 */
	public double Turnover;
	/**
	 * 持仓量<br>
	 * C type : TThostFtdcLargeVolumeType
	 */
	public double OpenInterest;
	public CThostFtdcMarketDataLastMatchField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("LastPrice", "Volume", "Turnover", "OpenInterest");
	}
	/**
	 * @param LastPrice 最新价<br>
	 * C type : TThostFtdcPriceType<br>
	 * @param Volume 数量<br>
	 * C type : TThostFtdcVolumeType<br>
	 * @param Turnover 成交金额<br>
	 * C type : TThostFtdcMoneyType<br>
	 * @param OpenInterest 持仓量<br>
	 * C type : TThostFtdcLargeVolumeType
	 */
	public CThostFtdcMarketDataLastMatchField(double LastPrice, int Volume, double Turnover, double OpenInterest) {
		super();
		this.LastPrice = LastPrice;
		this.Volume = Volume;
		this.Turnover = Turnover;
		this.OpenInterest = OpenInterest;
	}
	public static class ByReference extends CThostFtdcMarketDataLastMatchField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcMarketDataLastMatchField implements Structure.ByValue {
		
	};
}
