package quantbox;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * 投资者保证金率模板<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:5119</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CThostFtdcMarginModelField extends Structure {
	/**
	 * 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	public byte[] BrokerID = new byte[11];
	/**
	 * 保证金率模板代码<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	public byte[] MarginModelID = new byte[13];
	/**
	 * 模板名称<br>
	 * C type : TThostFtdcCommModelNameType
	 */
	public byte[] MarginModelName = new byte[161];
	public CThostFtdcMarginModelField() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("BrokerID", "MarginModelID", "MarginModelName");
	}
	/**
	 * @param BrokerID 经纪公司代码<br>
	 * C type : TThostFtdcBrokerIDType<br>
	 * @param MarginModelID 保证金率模板代码<br>
	 * C type : TThostFtdcInvestorIDType<br>
	 * @param MarginModelName 模板名称<br>
	 * C type : TThostFtdcCommModelNameType
	 */
	public CThostFtdcMarginModelField(byte BrokerID[], byte MarginModelID[], byte MarginModelName[]) {
		super();
		if ((BrokerID.length != this.BrokerID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.BrokerID = BrokerID;
		if ((MarginModelID.length != this.MarginModelID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.MarginModelID = MarginModelID;
		if ((MarginModelName.length != this.MarginModelName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.MarginModelName = MarginModelName;
	}
	public static class ByReference extends CThostFtdcMarginModelField implements Structure.ByReference {
		
	};
	public static class ByValue extends CThostFtdcMarginModelField implements Structure.ByValue {
		
	};
}
